### ISSUE TITLE
Cannot embed YouTube video

### ISSUE THREAD

**Issue by sakhmedbayev** [michelson/dante2#102]
![mar-21-2018 22-08-50](https://user-images.githubusercontent.com/8005396/37721755-8bb4e564-2d54-11e8-9f50-f241755b11e9.gif)

I am trying to add a youtube video, so far no luck. I am using dante-test repo

**Comment by vinceprofeta** [comment]
@sakhmedbayev do you have the proper API keys for embedly?

**Comment by sakhmedbayev** [comment]
Thank you @vinceprofeta for the response. Can dante be used without embed.ly?

**Comment by michelson** [comment]
of course, but you have to implement your own backend . just look into https://oembed.com/ and use some of many oembed clients out there, and make sure you set the `oembed_uri` option for dante2 in order to work with a custom endpoint

**Comment by sakhmedbayev** [comment]
Hi @michelson! I tried to set oembed_uri in the following manner:

`defaultOptions.oembed_uri = 'https://api.embed.rocks/api';`

It did not work for me.

**Comment by michelson** [comment]
Hi , please check documentation in https://michelson.github.io/dante2/#/src-widgets in Embed Video. there is an example on how you can set the embed url on embed component
