### ISSUE TITLE
How to set content after initialisation?

### ISSUE THREAD

**Issue by vephinx** [michelson/dante2#11]
After initialising Dante (like so):

```javascript
  editor = new Dante({
    el: "app",
    content: JSON.parse(content),
    ...
  });
  editor.render();
```

How can you change the content and force Dante to render again?
I tried running `editor.editor.setPreContent(JSON.parse(newContent));`and `editor.options.content = JSON.parse(newContent);` followed by `editor.editor.render();` and `editor.render();`, to no effect.

I looked at [app/components/App.cjsx](https://github.com/michelson/dante2/blob/master/app/components/App.cjsx) but I couldn't figure it out. 

Thanks for your help!

**Comment by michelson** [comment]
ok, after you set the content you then must trigger the `onChange` event on
editor, so:

`editor.editor.onChange(editor.editor.state.editorState)`

best!

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by vephinx** [comment]
So I do:

```javascript
editor = new Dante({
    el: "app",
    content: window.PocData,
    ...
});
editor.render();

newContent = {"entityMap":{},"blocks":[{"key":"a2due","text":"This is a test.","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]};
// editor.editor.setPreContent(newContent);
editor.options.content = newContent;
editor.editor.onChange(editor.editor.state.editorState);
```

and nothing happens. Also with the commented out line commented in instead, nothing happens. What am I doing wrong?

**Comment by michelson** [comment]
Hi @vephinx 
Uhm , I guess there isn't a direct way to do this, but right now it can be done with the draft-js api directly, (that's the main idea of this editor as it's based on draft is that we can use draft-js api), I will suggest that you read the documentation of draft-js and understand how `editorState` works,
there are some modifiers which enables the content modification, https://facebook.github.io/draft-js/docs/api-reference-modifier.html

you have to implement 3 steps:
1. set the new content (using modifier , replace-text,  for example)
2. push new content using draft's `EditorState.push(`
3. call editor `onChange`

`handleHTMLPaste`
look into [App.js paste handler](https://github.com/michelson/dante2/blob/0fa0864564c60209424c549331e8044f449a2ed9/app/components/App.cjsx#L622) that could give yo some pointers on how to do this.

what is the use case for this ? are you trying to update content in the middle of the edition? just curiosity

**Comment by zcmgyu** [comment]
Same in React

```
componentWillMount() {
    this.data = {"entityMap":{},"blocks":[{"key":"761n6","text":"THIS IS TEST: 11111","type":"header-one","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}
}

componentDidMount() {
    console.log('componentDidMount')
    this.data =  {"entityMap":{},"blocks":[{"key":"761n6","text":"THIS IS TEST: 22222","type":"header-one","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}
}

<PostEditor config={{
                    upload_url: "http://localhost:9292/uploads/new",
                    debug: true,
                    data_storage: {
                    interval: 1000,
                        url: "/store",
                        save_handler: this.handleOnSave
                    }
                }}
                    content={this.data}
                />
```

**Comment by michelson** [comment]
Hi , My technique is as follows:

```javascript

  renderEditor(){
    if (!isEmpty(this.props.article) && !this.state.loading ){
      return <DanteApp
        ref="editorApp"
        content={JSON.parse(this.props.article.body)}
        //key={this.props.location.key}
        config={  { debug: true} } 
      />
    } else {
      return <Loader/>
    }                         
  }

```

this way when the content is changed and not loading then you render the editor. so it will refresh the content. obviously you have to manage the loading staten and build your own loader component in order to render

cheers

**Comment by zcmgyu** [comment]
OMG.  I appreciate your response. Have nice day.
