### ISSUE TITLE
How exactly save_handler works?

### ISSUE THREAD

**Issue by sakhmedbayev** [michelson/dante2#110]
I am trying to use Dante2 with a graphql server. For that matter, I want to use mutation function `saveDanteDraft` to save content. 

Would it be enough, if I just add a custom solution to `save_handler`? Something like following:

```
save_handler: (editorContext, content) => {
        return this.props.saveDanteDraft(editorContext);
      },
```

**Comment by michelson** [comment]
yes , save handler will override the query
fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
