### ISSUE TITLE
The medium (+) Tooltip to upload image not works on Mobile

### ISSUE THREAD

**Issue by jerryc-nguyen** [michelson/dante2#111]
Hi, many thanks for your awesome editor. But I do not see the (+) Tooltip on mobile. Does Dante2 support it on mobile? I can not see any document about it.
Looking forward to hearing from you or anyone resolved this issue.
Thanks.

**Comment by jerryc-nguyen** [comment]
Sorry, I just checking DOM then see it's overflow the screen area. The css left property is not suitable on mobile. Can you update the editor to support mobile?

**Comment by jerryc-nguyen** [comment]
I just check if mobile then override the css left property of popup to suitable value. Thanks

**Comment by michelson** [comment]
I @jerryc-nguyen , I would love to see a PR on this, or at least show us which css you've used to include it in the source
thanks!

**Comment by AndrewBMartin** [comment]
@michelson would be happy to make a PR for this. Can fix it in the browser but can't find in the codebase where the "top" and "left" attributes on the inlineToolTip are set when the "is-active" class is added. Can you point me in the right direction?
