### ISSUE TITLE
Icons not showing up for image popovers?

### ISSUE THREAD

**Issue by benallfree** [michelson/dante2#116]
I'm doing `import 'Dante2/dist/DanteStyles.css'` in my `index.js` of my React app, and it almost works, but not for image popovers.

![Image popover icons not showing](https://www.evernote.com/l/AQc-4RDEcrJKRpTXyMgDsB48GPD6A_P5KIsB/image.png)

But normal popovers do show icons:

![Normal popover icons show](https://www.evernote.com/l/AQdlulbiCcdKL7SVyCEpmc7kG45mGswwkigB/image.png)

Thanks for any help :)

**Comment by michelson** [comment]
fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
