### ISSUE TITLE
Popover vertical offset wrong?

### ISSUE THREAD

**Issue by benallfree** [michelson/dante2#117]
Maybe someone can help me with a styling issue? I am using Semantic UI and I noticed that when I place an `<h2>` element above the editor container, it throws off the popover vertical offset.

![vertical offset wrong](https://www.evernote.com/l/AQcjrNj2eglPCrvAVWa_PlhLY9UPN4bcRZMB/image.png)

If I remove it dynamically using the chrome debugger, the next popover is correct:

![now it's fixed](https://www.evernote.com/l/AQdsF6X0soROIIirvI61DTwleH0N9Xlm8TwB/image.png)

So I assume maybe Dante is assuming there is no element above it? Is that a bug?

**Comment by michelson** [comment]
fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
