### ISSUE TITLE
Image can not be deleted when pressing Del key

### ISSUE THREAD

**Issue by dakur** [michelson/dante2#118]
When I click on an image and press `Del` key, it deletes a break line under the image instead of deleting the image itself, which causes in very confusing state. This is a bug from UX point of view.

Try it on the animated image in here: https://michelson.github.io/dante2/ The headline becomes image caption.

Win 10, Firefox Dev Edition 62.0b9 (64bit)

**Comment by jkuchar** [comment]
Confirmed on Safari/Mac (pressing Fn+Backspace on image)

**Comment by michelson** [comment]
I've released a new version and it seems it is working as expected now. 
could you check if the demo has de delete image working?
