### ISSUE TITLE
Simple demo code

### ISSUE THREAD

**Issue by cmmartin** [michelson/dante2#121]
It would be really helpful to add a simple working example. I'm trying to use this library with React, but struggling to get it running. I finally figured out that I need to import it like this...

```
import { DanteEditor } from 'Dante2'
```

But now I get...

TypeError: Cannot read property 'map' of undefined

**Comment by codev0** [comment]
@cmmartin Hi, you can see how to use dante2 in [this](https://github.com/michelson/dante2-tests) repo
