### ISSUE TITLE
Wrong toolbar position

### ISSUE THREAD

**Issue by codev0** [michelson/dante2#123]
Hi there,
How can I fix this,
![](https://i.imgur.com/gY6c5Kf.png)
![](https://i.imgur.com/rzYlSGA.png)

I used [dante2-tests](https://github.com/michelson/dante2-tests) repo for example, and as CSS library used bulma.

**Comment by michelson** [comment]
Hi @codev0 . This is fixed on a pre release. https://github.com/michelson/dante2/pull/122

I hope to release this soon, meanwhile you can try that and tell us if that's working for you. the examples and documentation are included. It's around the corner I'm just polishing some details.
I'm using bulma for the examples site too!

**Comment by michelson** [comment]
fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
