### ISSUE TITLE
How can handle image adding event?

### ISSUE THREAD

**Issue by codev0** [michelson/dante2#124]
I need to add predefined figcaption after the image is added. Does dante have that kind of capability?

**Comment by michelson** [comment]
Hi @codev0 , I'm afraid Dante does not do this as a feature, but you could do that programmatically with the draft API https://draftjs.org/docs/api-reference-modifier.html , check replace text part.
but this is a good feature request to keep in mind

**Comment by codev0** [comment]
@michelson of course thanks for your responsiveness
