### ISSUE TITLE
How Can we handle custom image upload and video upload ?

### ISSUE THREAD

**Issue by Sanjay007** [michelson/dante2#126]
I want to controll image upload and video uploads using a callback.Can you tell me the callback to my component that i need to pass as a prop?

One more question - how can i contribute to this project?

**Comment by michelson** [comment]
Hi @Sanjay007 .

check the documentation `Upload Url Callback`section on widgets https://michelson.github.io/dante2/#/src-widgets
also you can check all the config options in the [image block](https://github.com/michelson/dante2/blob/master/src/editor/components/blocks/image.js#L354) 
If you are interested in contribute just clone and send a PR

best !
