### ISSUE TITLE
Incompatible with React 16?

### ISSUE THREAD

**Issue by blnk-space** [michelson/dante2#127]
```
Uncaught Error: Element ref was specified as a string (editor) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
```

This error comes up for many components like "image_popover" etc. Can we move from String refs to function refs or use React.createRef? I tried basic debugging but wasn't successful. I would like to include Dante2 in a commercial project after purchasing the licence; however; the project is in React 16 and I just can't get it to work. Let me know if anything can be done! thanks

**Comment by michelson** [comment]
Hi @blanck-space , I've noted this too recently when i've integrated this into a project. it seems to be the refs points to a component and not to a ref. I will fix that soon. 
meanwhile try to use this versions:

```
"Dante2": "^0.5.0-rc5",
"react": "^16.2.0",
"react-dom": "^16.2.0"
```

also you can alias the react version in webpack

```
  resolve: {
    alias: { 'react': path.resolve(__dirname, '../../node_modules', 'react') }
  }
```

please let me know it is working for you

**Comment by blanck-space** [comment]
Great temporary fix! However I'm tuned in for a final solution as well. I'd love to see how you fix this it made me stay up all night to no avail!
Let me know how to purchase a license for this as I'll be using this on one commercial website.

Also; please let me know if it's welcome for me to create a pull request where I expose an "onChange" handler; that gets called each time the editor state is changed. This makes it easy for people like me who want more control over the component; for example, keep saving the editor state in React component state and then on user action; initiate a "save" event that saves everything to server.

This would also help Dante2 to become more agnostic and compatible with redux-saga as well!

**Comment by blanck-space** [comment]
currently; I am making it work with 
```
          data_storage={{
            save_handler: (state, content) => {
              return console.log(state, content);
            },
            interval: 1500,
            url: '/store',
            method: 'POST',
          }}
```

It's working well for me to do what I need to do; still let me know your thoughts on whether it's welcome to expose an onStateChange handler

**Comment by blanck-space** [comment]
I'm going to purchase that license this week, before making the website live.
I have also found another bug. After following your instructions of webpack configuration to alias and use the specific version of React; everything worked except Dante would cause an error while hydrating content from a previously saved entry to database. Creating an issue and a relevant PR about it today or tomorrow soon as I get time!

**Comment by SeunghunSunmoonLee** [comment]
still not working Uncaught (in promise) Error: Cannot find module "prismjs"

**Comment by michelson** [comment]
Install the missing module

**Comment by SeunghunSunmoonLee** [comment]
I ran exactly like you ran on dante2-test repository.

Can you provide instructions how to import and use this library with react 16 ?

**Comment by michelson** [comment]
Hi. Please read the documentation site . And report the version of dante2
that is causing issues

**Comment by blanck-space** [comment]
@SeunghunSunmoonLee after installing prismjs everything works as expected while editing. However there is another bug in case you're fetching from database and try to initialise Dante2 editor which i'll be addressing soon as i get some time. However, to make things work as is; just do 
`npm install prismjs --save`

**Comment by rambabusaravanan** [comment]
@blnk-space seems a fake url is needed so that it will pass the validation (which is actually required for ajax call) as per the line
https://github.com/michelson/dante2/blob/7f098549570565985a64df1d0d4ece18caa2b8b6/src/editor/utils/save_content.js#L18

sample workaround (working fine)
https://codesandbox.io/s/1vp9p54rr4

Hence created a PR #135  by adding the required validation to consider save_handler where no more fake URL is needed. @michelson kindly verify and merge

**Comment by michelson** [comment]
fixed in rc6 , thanks!
