### ISSUE TITLE
Custom image upload handler

### ISSUE THREAD

**Issue by LeonidPelyhivskyi** [michelson/dante2#128]
We use custom image upload workflow in our application. I can't pass upload_url to image widget. It would great to have the possibility to add custom_upload_callback, I saw that you use the similar way for data_storage. Do you have a plan to do it? Can I create PR with custom_upload_callback for images?

**Comment by michelson** [comment]
indeed there is an `upload_callback ` option for upload widget. did you try that ?

**Comment by LeonidPelyhivskyi** [comment]
Yes, I tried it but it doesn't work. As I understood from documentation this method called after image uploaded. Source code also looks like that this callback called only after image uploaded (https://github.com/michelson/dante2/blob/master/src/editor/components/blocks/image.js#L245).

But...
I researched source code one more time and I found one more callback ```upload_handler``` (https://github.com/michelson/dante2/blob/master/src/editor/components/blocks/image.js#L225). Please update the documentation. This is one that I want.  

The issue can be closed!

Thank you!

**Comment by michelson** [comment]
@LeonidPelyhivskyi my apologies  🙏 ! , you are right. `upload_handler` is what you want

**Comment by LeonidPelyhivskyi** [comment]
no worries ;) 
Example for people who will have the same problem: 
```
<Dante widgets={[
    ImageBlockConfig({
        options: {
            upload_handler: async (file, imageBlock) => {
                try {
                   const url = await my_custom_callback(file);
                   imageBlock.uploadCompleted(url); //  this needed to update editor state
                } catch (e) {
                   imageBlock.uploadFailed(); //  this needed to update editor state
                }
            };
        }
    })
]} />
```

**Comment by michelson** [comment]
nice! thanks @LeonidPelyhivskyi 👏 👏
