### ISSUE TITLE
Is there an alternative to save_handler ?

### ISSUE THREAD

**Issue by thawankeane** [michelson/dante2#130]
Hi,
When I was writing some example code using Dante2 and I found some problems.

Reading the docs and some issues in the repo, I found the `save_handler` callback. I'm using like this:
```jsx
<Dante
    content={this.state.content}
    debug={true}
    data_storage={{
      interval: 1500,
      url: '/store',
      method: 'POST',
      save_handler: (editorContext, content) => {
        this.props.onChange(content)
      },
    }}
/>
```
But I want only to keep the Editor state into my component state, without make a HTTP request to a URL, and this was the first problem. When I commented the `url` and `method` keys the function has stopped working. Also when writing in editor (with `url` and `method` keys) and attach a image, the `save_handler` function stopped working too.

Is there an alternative to save my Editor state ? Like an traditional onChange props without external requests.

Thanks

**Comment by blanck-space** [comment]
There is no such functionality yet! You will need to use a fake URL like '/fakestore' which doesn't need to exist; as a workaround.

I am doing this for a production-ready app and it's got no tangible side effects.

Soon as michelson or hopefully if I find time; then I; expose a traditional onStateChange or something; I'm sure the docs and the repo would be updated accordingly.

There's more high priority things for @michelson to work on like refs issue with newer versions of React 16 etc; this workaround should cover most use-cases until then. You could try using Megadraft or something if that handler is of utmost value; however personally I have made myself free from using a third party CMS just by integrating Dante2!

**Comment by blanck-space** [comment]
also about 

> Also when writing in editor (with url and method keys) and attach a image, the save_handler function stopped working too.

I have been able to upload images without any issues; maybe you just need to use the right version?

`
    "Dante2": "^0.5.0-rc5",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
`

is a perfectly working config

**Comment by makayi** [comment]
Looking for the same solution. I hope we get the onchange Listener soon.

**Comment by michelson** [comment]
Hi please check the 0.5.0-rc7 version I've implemented the onChange callback-. examples added in demo page at `https://michelson.github.io/dante2/#/src-index` 

reopen if needed, thanks for report this
