### ISSUE TITLE
  SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by p8ul** [michelson/dante2#134]
Am using Dante2 with create react app and I am getting this error when running yarn run test
` Details:

    /Users/ke-c02pvr5wfvh3/projects/react/ah-maps-frontend/node_modules/Dante2/package/es/components/blocks/video.js:19
    import React from 'react';
    ^^^^^^

    SyntaxError: Unexpected token import

      1 | import React from 'react';
    > 2 | import { VideoBlockConfig } from 'Dante2/package/es/components/blocks/video';
        | ^
      3 | import { EmbedBlockConfig } from 'Dante2/package/es/components/blocks/embed';
      4 | import { PlaceholderBlockConfig } from 'Dante2/package/es/components/blocks/placeholder';
      5 | import { Container, Grid, Form } from 'semantic-ui-react';`

**Comment by michelson** [comment]
Hi @p8ul 
can you check if those files are present on the node_modules/Dante2 ? otherwise if you could share the repository to check it out would be great

**Comment by p8ul** [comment]
<img width="417" alt="screen shot 2018-12-12 at 18 42 40" src="https://user-images.githubusercontent.com/17355400/49880705-c5cff300-fe3d-11e8-8d39-621709e520b7.png">
I have those files, and the editor is working fine. But am getting issues when running test

**Comment by p8ul** [comment]
https://github.com/p8ul/ah-maps-frontend/blob/ft-create-articles-161255198/src/components/Article/index.js

https://travis-ci.org/andela/ah-maps-frontend/builds/466991740?utm_source=github_status&utm_medium=notification

**Comment by michelson** [comment]
it seems the file is present, but is not able to compile it
```

    /home/travis/build/andela/ah-maps-frontend/node_modules/Dante2/package/es/components/blocks/video.js:19
    import React from 'react';
           ^^^^^
```

I'll bet that's a babel issue. it's not compiling because the import is not valid without babel configuration. you could try out the `lib` flavor of the Dante2 package. 
so , import as `Dante2/package/lib/...` instead of `Dante2/package/es/...` .

please let me know if that working. 
btw, this is a interesting project that you are working on. Just wondering if have you check the [Dante-stories project ?](https://github.com/michelson/dante-stories)

best

**Comment by p8ul** [comment]
Thanks using `lib` flavor worked fine

Here is my refactored code 
`import { VideoBlockConfig } from 'Dante2/package/lib/components/blocks/video';
import { EmbedBlockConfig } from 'Dante2/package/lib/components/blocks/embed';
import { PlaceholderBlockConfig } from 'Dante2/package/lib/components/blocks/placeholder';`

**Comment by michelson** [comment]
nice, glad it work
