### ISSUE TITLE
0.5.0-rc7 not published on NPM yet?

### ISSUE THREAD

**Issue by wirelessed** [michelson/dante2#143]
Tried to import version 0.5.0-rc7 but npm/yarn is telling me only 0.5.0-rc1 is available?

**Comment by michelson** [comment]
put `"Dante2": "0.5.0-rc7",` in your package

**Comment by wirelessed** [comment]
![image](https://user-images.githubusercontent.com/180234/50748259-7087d580-1273-11e9-9670-129bb2421780.png)

Hi

I just realised that there are 2 Dante2s on the NPM registry. Hence my npm/yarn keeps getting the lowercase dante2 which is still the older version.
