### ISSUE TITLE
Video embed not working on demo

### ISSUE THREAD

**Issue by stefanocdn** [michelson/dante2#148]
When trying to paste youtube/vimeo link the video is not embedded on the demo
https://michelson.github.io/dante2

**Comment by michelson** [comment]
Hi, it seems that the secure url is not working due to iframely invalid
certificate. I hope they can fix that soon , otherwise we sould use the
unsecure (http) url


Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by stefanocdn** [comment]
Right now if I change if I change the endpoint to use http like so

` widgets={[
                VideoBlockConfig({
                  options: {
                    endpoint: "http://open.iframe.ly/api/oembed?origin=https://github.com&url=",
                  }
                }),`

I get the following error message

> This request has been blocked; the content must be served over HTTPS.

Is that what you were suggesting?
Thank you

**Comment by ALEUT** [comment]
> Right now if I change the endpoint to use http like so
> 
> ` widgets={[ VideoBlockConfig({ options: { endpoint: "http://open.iframe.ly/api/oembed?origin=https://github.com&url=", } }),`
> 
> I get the following error message
> 
> > This request has been blocked; the content must be served over HTTPS.
> 
> Is that what you were suggesting?
> Thank you

Looks iframely provides embed functionality on billable base, it's just demo for http protocol because almost all the sites works via https. You can use it free only if your site is hosted with http protocol, otherwise the code should be fixed to use billable version or some other service.

**Comment by michelson** [comment]
yes, for production apps you should use the paid version of embedly or another free alternative like https://noembed.com/

I will update the demo page soon . thanks for report this

**Comment by michelson** [comment]
fixed , noembed is the default endpoint for video embeds & links. released as version rc-0.5.0.rc-11
