### ISSUE TITLE
Import Inline Styles?

### ISSUE THREAD

**Issue by wirelessed** [michelson/dante2#149]
Hi, 

I'm trying to import my own inline styles (e.g. a superscript) however I could only find a way to import custom block styles, but no way to import custom inline styles?

Thanks!

**Comment by michelson** [comment]
Hi @wirelessed , what you mean with custom style ? `<sup>` is a html block, so it should be handled as a custom block, not an inline style. but, by the way, Dante handles inline styles. 
can you explain in more detail what are you trying to do ?

**Comment by wirelessed** [comment]
Hi @michelson 
Thanks for your suggestion.
Yes I guess `<sup>` can be a block instead of doing an inline style. I was planning to use a `<span class="some_style_here">my text</span>` but I guess a continuous block can work too.

**Comment by wirelessed** [comment]
Just wondering if there's a way to prop into `customStyleMap`?

**Comment by michelson** [comment]
inline styles are a data for block. check the editor data when use the color picker over a text, it generate the inline style. 
but, if you use a custom block you can use class names or inline styles on it

**Comment by wirelessed** [comment]
Do you have any sample code on how to create a superscript then? Because `<sup>` is more of a style applied to a few characters in an existing block, and not a standalone block by itself.
