### ISSUE TITLE
onChange not working in React component

### ISSUE THREAD

**Issue by nasiscoe** [michelson/dante2#150]
Novice React developer here.

I'm currently importing Dante `import Dante from 'Dante2';` and would like to maintain the serialized output of the Dante editor by setting it in state so that I can save it to a Firebase Realtime database on a button press.

When I use onChange and type into the editor, nothing happens.

`  <Dante
              body_placeholder={'Write your story...'}
              read_only={!this.state.editable}
              onChange={() => { console.log('This should log') }}
            />`

**Comment by michelson** [comment]
Hi @nasiscoe , which version are you using ? latest version is properly working check the las example at https://michelson.github.io/dante2/#/src-index

**Comment by nasiscoe** [comment]
I'm currently using `"Dante2": "^0.5.0-rc12",`. The example does work for me but my own implementation is still failing to log anything for some reason.

**Comment by michelson** [comment]
it's hard to tell then. can you share the implementation ?

**Comment by nasiscoe** [comment]
My apologies, I just got it working by manually installing the `prismjs` package (via `npm i prismjs`). Is that package a dependency that should've installed when I installed Dante2, or is that an error on my end?

**Comment by michelson** [comment]
Hi @nasiscoe , yes it's present on the package dependences

**Comment by maxnowack** [comment]
@michelson `prismjs` is present in the `devDependencies` which are not installed automatically from npm

**Comment by michelson** [comment]
thanks  @maxnowack and @nasiscoe , latest version sets prism as dependence in package.json

**Comment by KumarAbhirup** [comment]
Hey, same problem here. Not able to `console.log` a single thing `onChange`. Please help, Dante2 is awesome 😍

**Comment by michelson** [comment]
Hi , try installing version 0.5.0-rc16, let me know it it does the job. 

cheers

**Comment by KumarAbhirup** [comment]
Thanks 👍 it's working
