### ISSUE TITLE
How to update content after initial render

### ISSUE THREAD

**Issue by jamesvillarrubia** [michelson/dante2#151]
I'm looking to have 1 button outside of the Dante editor that adds text to the end of the editor.  The other imports text from a DB and puts it in.

Right now my solution is to change `<Dante key={this.state.key} content={this.state.content}/>` by calling:
```
 this.setState({
      loaded:true,
      content: newContent,
      editorKey:this.state.editorKey+1
    },()=>{
      console.log('Loaded true')
    })
```

This obviously obilerates the old Dante instance and rebuilds a new one.  But I have no idea how else to do it.   I would love to be able to preserver undo/redo chain.  I can't seem to find a function that can access the DraftEditor underneath the covers or that can actually push the DraftEditor update and get it to show.

I did try fiddling with: `this.editorState = EditorState.push(this.editorState, stateFromMarkdown('...'))` but with no luck.

Any simple example would be appreacited!

**Comment by michelson** [comment]
You could do that implementing a toolip. Look at `https://michelson.github.io/dante2/#/src-tooltips`
tooltips are those components that interacts with the editor but are not included in the content. For your use case ( external button that adds text ) is exactly what you need. 
This kind of component has the editor context as props so you can interact & update the editorSate

best!
