### ISSUE TITLE
DanteTooltipConfig is not defined

### ISSUE THREAD

**Issue by erdalstk** [michelson/dante2#153]
Hi, thank you very much for such a beautiful Draft Js Editor but i couldn't define the custom tooltip options. My code is here, copy and pasted from Dante2 documentation.

`<Dante  content={null}
                        tooltips={[
                            DanteTooltipConfig({
                                widget_options: {
                                    block_types: [
                                        {
                                            label: 'bold', 
                                            style:'BOLD', 
                                            type: 'inline', 
                                            icon: FormatBold
                                        },
                                        {
                                            label: 'italic',
                                            style: 'ITALIC',
                                            type: 'inline',
                                            icon: FormatBold,
                                        },
                                    ],
                                },
                            }),
                        ]}
                    />`

I don't want to display all tooltip options on text select. I used the code as in the demo [here](https://michelson.github.io/dante2/#/src-tooltips) #Widget options but it gives this error **"DanteTooltipConfig is not defined"**. 

I looked older issues and make lots of research but i couldn't achieve the expected result.
Which is i want to display only "bold" and "italic" options as shown in demo.

Documentation doesn't say how to define options and solve this issue.

**Comment by michelson** [comment]
Have you imported `DantetooltipConfig` ?

**Comment by mbm-michal** [comment]
@michelson I had the same issue as documentation does not show full. I've imported that way: 

`import { DanteTooltipConfig } from "Dante2/package/lib/components/popovers/toolTip"`

is that the correct way?

**Comment by michelson** [comment]
Try to import the `es` version, like

`import { DanteTooltipConfig } from 'Dante2/package/es/components/popovers/toolTip.js' `
