### ISSUE TITLE
.hidden class styling breaks my application's UI

### ISSUE THREAD

**Issue by kwayebopp** [michelson/dante2#161]
I noticed that the stylesheet for Dante2 is present throughout my application, even in scenes where the editor is absent. Unfortunately, this has broken some of the other UI libraries I use due to the shared use of the `.hidden` class. Is it possible to only load the stylesheet when the Dante component is about to be mounted onto the DOM? Otherwise, could the `.hidden` class be given a `Dante` prefix (e.g. `.Dante-hidden`)?

**Comment by kwayebopp** [comment]
The offending line of code exists in the repo [here](https://github.com/michelson/dante2/blob/af762a5e84088f0597f357627c2da79b88344d78/src/editor/styles/dante/_utilities.scss#L57). In the actual node_module package, the injected css can be found in `Dante2/package/Dante.cjs.js` at line 1569. I've tried removing the `.hidden` style from the stylesheet in Chrome/Firefox dev tools and nothing _appears_ to have broken. 

If someone else can also confirm that removing the `.hidden` styling doesn't break the UI, I can make a PR. I would fork this repo and make a personal npm package, but I don't know how ¯\_(ツ)_/¯

**Comment by michelson** [comment]
hi @kwayebopp please go ahead, as far as I know we don't use the `.hidden` class
