### ISSUE TITLE
Weird positioning of editor toolbar.

### ISSUE THREAD

**Issue by Bodacious** [michelson/dante2#17]
The text editor toolbar is not positioning well for me.

As a page gets longer and longer, the toolbar moves further from the are where I'm writing...

<img width="836" alt="screenshot 2017-01-05 12 09 15" src="https://cloud.githubusercontent.com/assets/73998/21680176/ee0fde64-d33f-11e6-99c6-4096c962dce2.png">

Any idea how I can fix this?

**Comment by Bodacious** [comment]
<img width="877" alt="screenshot 2017-01-05 12 10 59" src="https://cloud.githubusercontent.com/assets/73998/21680195/0bc06208-d340-11e6-9274-92b6a4354b49.png">

**Comment by reimertz** [comment]
Btw, just curious, @Bodacious, what are you building with this tool? :)

**Comment by michelson** [comment]
@reimertz are you having the same issue in your implementation ?

**Comment by reimertz** [comment]
@michelson yep
![image](https://cloud.githubusercontent.com/assets/625287/21715832/1540dfb6-d407-11e6-88b0-7404d04dcb19.png)

**Comment by michelson** [comment]
This is weird, I will check this one over the weekend with a clean implementation , are you using bootstrap too @reimertz ?

**Comment by Bodacious** [comment]
![dante-mobile-bug](https://cloud.githubusercontent.com/assets/73998/21754150/27c5f260-d5f2-11e6-9d99-8574ca6ac0ca.gif)

**Comment by Bodacious** [comment]
@michelson Any progress on this? We're ready to go live with our platform once this issue is fixed.

**Comment by reimertz** [comment]
@Bodacious if you want to haste the progress, you could help out and try to fix it yourself.
A good start would be to look at 
 - [toolTip.csjx](https://github.com/michelson/dante2/blob/master/app/components/popovers/toolTip.cjsx)
-  [addButton.csjx](https://github.com/michelson/dante2/blob/master/app/components/popovers/addButton.cjsx)
- [_tooltip.scss](https://github.com/michelson/dante2/blob/master/app/styles/dante/_tooltip.scss)

😍

**Comment by michelson** [comment]
Hi @Bodacious , Mystery solved! I've double check the integration on the `reformer` site. and I've found that for some reason the bootstrap classes (col-x) are messing the position of the editor, Specifically the position property

try to remove the position:relative  the col-x-x classes or set position:inherit for that specific element and it will work fine.

![image](https://cloud.githubusercontent.com/assets/11976/21987802/a9c50412-dbe3-11e6-9994-60fbb3c3621a.png)

**Comment by Bodacious** [comment]
Thanks!

My solution for this, and for the mobile (320px) screen wobbling was the following:

``` sass
.editor_wrapper
  position: inherit
  
.dante-menu
  max-width: 100vw

.dante-menu-buttons
  overflow: hidden

```

**Comment by michelson** [comment]
thanks for sharing @Bodacious !
