### ISSUE TITLE
CompositeEditor is not defined.

### ISSUE THREAD

**Issue by mrfambo** [michelson/dante2#171]
Hello, i am implementing

`<Dante
                                debug={true}
                                widgets={[CodeBlockConfig()]}
                                decorators={context => { return new MultiDecorator([ PrismDraftDecorator({ prism: Prism }), new CompositeDecorator([ { strategy: findEntities.bind(null, 'LINK', context), component: Link, }, ]), ]) }}
                            />`

After a huge stress i came to know how to get

1. CodeBlockConfig()
2. PrismDraftDecorator()

Now i am very confused about:

1. CompositeDecorator
2. findEntities
3. Link

Seems like documentation is very pro level not for beginners. Once i have the knowledge i will surely PR and update and the Docs for basic level too !!!

**Comment by mrfambo** [comment]
DraftJS Documentation and Naming Conventions are so confusing and it makes you feel so terrible !! I want to know how to get Composite Decorator, findEntities and Link.

**Comment by michelson** [comment]
@mrfambo sorry for the delay , do you still have issues with this ?
check https://github.com/michelson/dante2/blob/master/src/docs/theme.js there you have a complete implementation

feel free to reopen if needed

best
