### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by xanderjakeq** [michelson/dante2#176]
Hi, I am following this [page](https://michelson.github.io/dante2/#/src-index) to learn how to use Dante2.

Based on what I see, I have to do:
`yarn add Dante2@next`
then
```
//import react stuff
import Dante from 'Dante2';

export default const Editor = (props) => {
  return (
    <Dante/>
  )
}
```
But I get this error: `Element ref was specified as a string (editor) but no owner was set.`

What am I doing wrong?
thanks :)

**Comment by michelson** [comment]
Hi @xanderjakeq , 
which version of dante are you using?
which version of react are you using ?

can you make a codepen to debug / send entire exception log ?

regards
