### ISSUE TITLE
content property not updating the view

### ISSUE THREAD

**Issue by LorenzoBernaschina** [michelson/dante2#177]
Hi, amazing library!!

I have an issue when I try to update the content property with a new article schema I get from an API.

I am using:
Dante2 **0.5.0-rc16**
React **16.9**

I am working with hooks and when I set the state and pass it to the content property, the view doesn't update and I can see only 'Write your story'

Moreover, I see in console these warnings:
> componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: DanteImagePopover, DanteInlineTooltip, DanteTooltipColor

> react-dom.development.js:12029 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: DraftEditor

Could you please check it out? Thank you guys for the amazing job you have done so far!!

**Comment by michelson** [comment]
Hi, can you check the version rc20 and tell us how it goes for you?

Best

**Comment by LorenzoBernaschina** [comment]
It fails to compile:
> ./node_modules/Dante2/package/umd/Dante.js
> Module not found: Can't resolve '@emotion/styled' in '~/node_modules/Dante2/package/umd'

**Comment by michelson** [comment]
Yes !, you have to install those missing dependences, with yarn add

**Comment by LorenzoBernaschina** [comment]
Oh I forgot, sorry! Anyway the problem persists but now I get only this warning:

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: DanteImagePopover, DanteInlineTooltip, DanteTooltipColor

**Comment by michelson** [comment]
Hi @LorenzoBernaschina ,
I've made some fixes in order to silence the warnings and I've updated the content update from props. You can check the example here. https://michelson.github.io/dante2/#/src-content-update

if you want to try this please update the package to 0.5.0-rc21

thanks for report this!

**Comment by LorenzoBernaschina** [comment]
Hi @michelson ,
it works perfectly, thank you very much!!!

**Comment by LorenzoBernaschina** [comment]
Hi @michelson ,
I have this situation:
`<Dante
        content={globalArticleState.content}
        onChange={(editor: any) => { 
          globalArticleActions.setContent(JSON.stringify(editor.emitSerializedOutput()))
      }} />`
globalArticleActions updates the globalArticleState variable and I get this error when I run the app

> Uncaught Invariant Violation: invalid RawDraftContentState
>     at invariant 
> index.js:1375 The above error occurred in the <DanteEditor> component:
>     in DanteEditor (created by Dante)
>     in div (created by Context.Consumer)
>     in Styled(div) (created by Dante)
>     in ThemeProvider (created by Dante)
>     in Dante (at App.tsx:21)
>     in div (at App.tsx:20)
>     in div (at App.tsx:16)
>     in App (at src/index.tsx:8)
> 
> Consider adding an error boundary to your tree to customize error handling behavior.
> Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Is it possible to update the state of a variable that is used to set the content of the editor at the beginning?

Thank you

Lorenzo
