### ISSUE TITLE
Migrating from coffeescript to babel?

### ISSUE THREAD

**Issue by reimertz** [michelson/dante2#18]
Just wonder the reasoning behind using coffeescript rather than es6 transpiling with babel?
It seems the majority of the community has moved away from coffeescript.

I am about to get Dante to work as a React component but the issue is that I have to have a coffeescript loader to be able to import it (except some weird issues with your fonts, but I'm about to fix that as well).

**Comment by michelson** [comment]
Hi @reimertz , yeah I know the community has opted for es6, but I feel more productive in coffeescript and to be honest I don't see any advantages in es6 in terms of syntax over ☕️ . But I will be agree to move the code to es6, I understand that using es6 will be more community friendly and easier to integrate. so  👍

**Comment by michelson** [comment]
this migration was made since 0.3.0 version

**Comment by reimertz** [comment]
@reimertz 🙏 @michelson
