### ISSUE TITLE
onChange does not fire for initial content

### ISSUE THREAD

**Issue by thith** [michelson/dante2#185]
When the Dante renders, it always fires `onChange` with content of blank, and does not fire `onChange` for initial content.

```js
<Dante
	content={some valid initial content}
	onChange={console.log}
/>
```
`onChange` fired with content of blank instead of initial content.

**Comment by michelson** [comment]
Hi @thith , which version are you using ?

**Comment by thith** [comment]
> Hi @thith , which version are you using ?

@michelson I use `0.5.0-rc21`. Dante2 raise the **first** `onChange` event with context of a blank text (it fires when rendering, no manual editting yet). Subsequent onChange events are passed the correct values.

**Comment by thith** [comment]
It seems `editor.emitSerializedOutput()` works so I use it instead of `save.editorContent`.
