### ISSUE TITLE
Clear content on component unmount

### ISSUE THREAD

**Issue by nightw0lff** [michelson/dante2#194]
How do i clear the content from the editor when component is unmounted?

**Comment by michelson** [comment]
Hi , what you mean with clear ? unmounted components are cleared. 
Can you re elaborate your question ?

**Comment by nightw0lff** [comment]
Sorry, ok. So basically i have a Drawer component with the editor inside of it. When i close the Drawer component and reopen the Editor still has whatever I wrote there, does the editor state has any method to clean up the content written?

**Comment by michelson** [comment]
you have two alternatives, 
1) set a empty content on editor when the drawer is toggled
2) re render editor on drawer open in order to re-instantiate, like this:

{ this.state.open && <Dante ../> }

**Comment by nightw0lff** [comment]
hm i see, thanks for the tip.
