### ISSUE TITLE
Content initialization via useState is not working with latest react

### ISSUE THREAD

**Issue by avifatal** [michelson/dante2#198]
Hi,
When I try to load the content via useState it is not appearing: https://stackblitz.com/edit/react-prwej4

But, if I do it directly, it does work: https://stackblitz.com/edit/react-5jpjqs?file=index.js

Any idea how I can do it with useState?

Thanks

**Comment by michelson** [comment]
Hi @avifatal , thanks for report this, 

I've deprecated this on the [current version](https://github.com/michelson/dante2/pull/195/files#diff-23e51f30a06a1a4ae426cb6144b56ce4R120), but thinking twice its better to have this feature than not. Be aware that if you mutate the state on content the editor will reinitialize the content but you will loose the cursor selection. in other works if you intent to make editor uncontrolled mutating the `content` value you will get a nasty behavior. use it only for initialize content

I've deployed version rc23 , here is the example https://michelson.github.io/dante2/#/src-content-update. 

I will close this now , but it you get in to troubles please reopen this issue

**Comment by avifatal** [comment]
Thanks.
Can you please try and correct my sample here: https://stackblitz.com/edit/react-prwej4 ?
