### ISSUE TITLE
How do you Import widgets like ImageBlockConfig and tooltips like DanteTooltipConfig

### ISSUE THREAD

**Issue by johnpaul89** [michelson/dante2#202]
./src/app/main/editor/TestEditor.js
  Line 22:21:  'ImageBlockConfig' is not defined  no-undef

Search for the keywords to learn more about each error.

I'm trying to import it like this  but I'm getting the above error.

import Dante from 'Dante2';
import {ImageBlockConfig} from 'Dante2';

**Comment by michelson** [comment]
Hi @johnpaul89 , import like this:
```js
import { ImageBlockConfig } from 'Dante2/package/es/components/blocks/image.js'
import { EmbedBlockConfig } from 'Dante2/package/es/components/blocks/embed.js'
import { VideoBlockConfig } from 'Dante2/package/es/components/blocks/video.js'
```
