### ISSUE TITLE
default_storage not calling endpoint

### ISSUE THREAD

**Issue by HugoSanchez** [michelson/dante2#203]
Hi!

I'm not being able to use the data_storage option to send the content to a basic backend endpoint that I've built with express.

Here's what I'm doing:

```
import React from 'react';
import DanteEditor from "Dante2";

const Editor = props => {

    const defaultOptions = {
        debug: true,
        read_only: true,

        xhr: {
            before_handler: () => console.log('Try1'),
            success_handler: () => console.log('Try2'),
            error_handler: () => console.log('Try3'),
        },

        data_storage: {
            url: 'http://localhost:8000/',
            method: "POST",
            success_handler: () => console.log('Succeeding'),
            failure_handler: () => console.log('Failing'),
            interval: 500,
            withCredentials: false,
            crossDomain: false,
            headers: {}
        },
    }

    return (
        <div className="Main">
               <DanteEditor  
                    content={null}  
                    config={defaultOptions}/>
        </div>
    );
}

export default Editor;

```
The editor works properly but no calls to the endpoint are being made.

Is there anything that I am missing? 

I'm expecting to receive a request to the endpoint but absolutely nothing happens, nothing gets console logged neither. I've tested the endpoint with postman and it works.

Any tips would be very appreciated.

Thanks!

**Comment by michelson** [comment]
try passing the data_storage as a prop like `DanteEditor
data_storage={myConfig} />`




Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by HugoSanchez** [comment]
That seems to work although I know have a CORS problem I need to solve first.

By the way, is there any way to get the content before the endpoint is called?

Thank you for getting back so quick!

**Comment by michelson** [comment]
the editor content is updated without needing to update your component
state.

if you want to get the content every time you have changes you can use
`save_handler:
func (editorContext, content)` and build your own ajax function.

also , there is indeed a `before_handler` but it's not returning the
content on the callback




Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by HugoSanchez** [comment]
Thank you for your help and sorry to ask you again, but can you please share an example of how to use "save_handler"?

I've tried using it like so, but nothing happens:
`
<DanteEditor  
                    content={null}  
                    config={defaultOptions}
                    data_storage={{save_handler: function(editorContext, content) {
                            console.log('Editor Context: ', editorContext)
                            console.log('Editor Content: ', content)
                    }}}/>
`

Not sure what I am doing wrong.

Thank you

**Comment by michelson** [comment]
sorry, use this structure, note the dummy url prop

```
data_storage={
{
url: "/",
save_handler: (editorContext, content)=>{ ... }
}
}
```



Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by HugoSanchez** [comment]
That worked, thanks so much and congratulations on the great work!

**Comment by michelson** [comment]
glad to work , @HugoSanchez !
