### ISSUE TITLE
content prop not rendering content.

### ISSUE THREAD

**Issue by HugoSanchez** [michelson/dante2#208]
Hey Michelson, 

I'm trying to have Dante 2 editor display some content (in the right format: {blocks: Array, entityMap: {}}) like so:

`<DanteEditor 
                        content={this.state.content} 
                        read_only={false}
                        config={this.options}
                        data_storage={this.storage}
                        default_wrappers={this.wrappers}/>
`

But nothing is being displayed. Any clues on what I might be missing?

Thank you!
Hugo

**Comment by mbm-michal** [comment]
@HugoSanchez you need to pass valid draftjs object. For example if you have your content saved as markdown you can format it to draftjs by using this module: https://www.npmjs.com/package/markdown-draft-js

**Comment by HugoSanchez** [comment]
Michelson, 

Apparently the problem was with the component life-cycle and not with the format. It's is now solved.

Thank you!

**Comment by anup-a** [comment]
@HugoSanchez  I'm facing similar problem could elaborate how you fixed it?

**Comment by anup-a** [comment]
@HugoSanchez thanks I figured that out.
