### ISSUE TITLE
Re-render blocks when cutting text

### ISSUE THREAD

**Issue by alihaddadkar** [michelson/dante2#209]
Hello
There's a problem with the draft-js.
When cutting the text, all blocks (image|embed) are re-rendered.
Blocks need to be rendered when there is a change.

**Comment by michelson** [comment]
can you give an example code or a .gif of the problem ?

**Comment by michelson** [comment]
I think this is how Draft-js works, when the editorState changes, all the components are re rendered.¿are you having perfomance issues?

**Comment by alihaddadkar** [comment]
You can see this issue in the dante2 demo.
add embed block to the editor. after, perform cutting on the text.

> can you give an example code or a .gif of the problem ?

**Comment by alihaddadkar** [comment]
> I think this is how Draft-js works, when the editorState changes, all the components are re rendered.¿are you having perfomance issues?

This issue only the case when cutting text.
Yes, I have a performance issue when the number of blocks increases.

**Comment by michelson** [comment]
no further details on this. so closing it
