### ISSUE TITLE
Is there any way i can change the embedly and use my own server 

### ISSUE THREAD

**Issue by dsslimshaddy** [michelson/dante2#21]
When adding a link it sends requet to 

`http://api.embed.ly/1/extract?key={KEY}&url={URL}&scheme=https`

How can i change it to something 

`http://custom.com/url?blahblah={}`

Could you point out the line of code ?

**Comment by dsslimshaddy** [comment]
Ok i got it but i want to know which return parameters are **compulsory required** by dante2

HERE is what i got from embedly but i dont think dante needs all return parameter.. so it would be great if you could point out which ones are necessary

{
	"provider_url": "https://www.youtube.com/",
	"description": "Mianwali \"A babe in the house is a well-spring of pleasure, a messenger of peace and love, a resting place for innocence on earth, a link between angels and men\" One brother is watching Cartoon film and the other is struggling to get comfortable zone. What a life in childhood...",
	"embeds": [],
	"safe": true,
	"provider_display": "www.youtube.com",
	"related": [],
	"favicon_url": "https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico",
	"authors": [
		{
			"url": "https://www.youtube.com/user/WajiNiazi",
			"name": "WajiNiazi"
		}
	],
	"images": [
		{
			"caption": null,
			"url": "https://i.ytimg.com/vi/AMHXM7QdOjA/hqdefault.jpg",
			"height": 360,
			"width": 480,
			"colors": [
				{
					"color": [
						79,
						77,
						77
					],
					"weight": 0.5705566406
				},
				{
					"color": [
						211,
						228,
						230
					],
					"weight": 0.1750488281
				},
				{
					"color": [
						8,
						12,
						13
					],
					"weight": 0.1591796875
				},
				{
					"color": [
						174,
						153,
						143
					],
					"weight": 0.0952148438
				}
			],
			"entropy": 5.74430271671,
			"size": 11499
		}
	],
	"cache_age": 86011,
	"language": "English",
	"app_links": [
		{
			"url": "vnd.youtube://www.youtube.com/watch?v=AMHXM7QdOjA&feature=applinks",
			"type": "ios",
			"namespace": "ai",
			"app_store_id": "544007664",
			"app_name": "YouTube"
		},
		{
			"url": "vnd.youtube://www.youtube.com/watch?v=AMHXM7QdOjA&feature=applinks",
			"type": "android",
			"namespace": "ai",
			"app_name": "YouTube",
			"package": "com.google.android.youtube"
		},
		{
			"url": "https://www.youtube.com/watch?v=AMHXM7QdOjA&feature=applinks",
			"type": "web",
			"namespace": "ai"
		},
		{
			"url": "vnd.youtube://www.youtube.com/watch?v=AMHXM7QdOjA&feature=applinks",
			"namespace": "twitter",
			"type": "ipad",
			"name": "YouTube",
			"id": "544007664"
		},
		{
			"url": "vnd.youtube://www.youtube.com/watch?v=AMHXM7QdOjA&feature=applinks",
			"namespace": "twitter",
			"type": "iphone",
			"name": "YouTube",
			"id": "544007664"
		},
		{
			"url": "https://www.youtube.com/watch?v=AMHXM7QdOjA",
			"namespace": "twitter",
			"type": "googleplay",
			"name": "YouTube",
			"id": "com.google.android.youtube"
		},
		{
			"path": "http/www.youtube.com/watch?v=AMHXM7QdOjA",
			"package": "com.google.android.youtube",
			"namespace": "google",
			"type": "android"
		},
		{
			"path": "vnd.youtube/www.youtube.com/watch?v=AMHXM7QdOjA",
			"package": "544007664",
			"namespace": "google",
			"type": "ios"
		}
	],
	"original_url": "https://www.youtube.com/watch?v=AMHXM7QdOjA",
	"url": "https://www.youtube.com/watch?v=AMHXM7QdOjA",
	"media": {
		"duration": 182,
		"width": 640,
		"html": "<iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FAMHXM7QdOjA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DAMHXM7QdOjA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FAMHXM7QdOjA%2Fhqdefault.jpg&key=d42b91026ea041c0875fd61ff736cb79&type=text%2Fhtml&schema=youtube\" width=\"640\" height=\"480\" scrolling=\"no\" frameborder=\"0\" allowfullscreen></iframe>",
		"type": "video",
		"height": 480
	},
	"title": "Mianwali (Child show Top Video) , (Funny and innocent Children)",
	"offset": null,
	"lead": null,
	"content": null,
	"entities": [
		{
			"count": 4,
			"name": "Mianwali"
		},
		{
			"count": 1,
			"name": "Shadi Nahi"
		},
		{
			"count": 1,
			"name": "The First Time"
		},
		{
			"count": 1,
			"name": "Best Scared Babies Videos"
		},
		{
			"count": 1,
			"name": "Mary Johnson"
		},
		{
			"count": 1,
			"name": "Muhammad Aslam Pervez"
		},
		{
			"count": 1,
			"name": "Cambodia"
		},
		{
			"count": 1,
			"name": "Rana Shahbaz"
		},
		{
			"count": 1,
			"name": "TeRi MeRi"
		},
		{
			"count": 1,
			"name": "MALIK"
		},
		{
			"count": 1,
			"name": "Funny Saraki Chacha Dance Choor Wala"
		},
		{
			"count": 1,
			"name": "Babylove"
		},
		{
			"count": 1,
			"name": "FailArmy"
		},
		{
			"count": 1,
			"name": "Abdul Basit"
		},
		{
			"count": 1,
			"name": "Edon Rexhepi"
		}
	],
	"favicon_colors": [
		{
			"color": [
				223,
				40,
				22
			],
			"weight": 0.0505371094
		},
		{
			"color": [
				249,
				244,
				245
			],
			"weight": 0.0119628906
		}
	],
	"keywords": [
		{
			"score": 118,
			"name": "duration"
		},
		{
			"score": 63,
			"name": "views"
		},
		{
			"score": 57,
			"name": "funny"
		},
		{
			"score": 40,
			"name": "mianwali"
		},
		{
			"score": 30,
			"name": "baby"
		},
		{
			"score": 26,
			"name": "compilation"
		},
		{
			"score": 23,
			"name": "kid"
		},
		{
			"score": 21,
			"name": "videos"
		},
		{
			"score": 20,
			"name": "basit"
		},
		{
			"score": 20,
			"name": "failarmy"
		}
	],
	"published": 1282848010000,
	"provider_name": "YouTube",
	"type": "html"
}

**Comment by michelson** [comment]
for the embed we use `images`, `url` , `title`, `description` and `provider_url`
for video we use `thumbnail_url` , `html`

**Comment by dsslimshaddy** [comment]
thanks
