### ISSUE TITLE
Anyone running this with CRA - 16.9+?

### ISSUE THREAD

**Issue by samuelcelko** [michelson/dante2#211]
Hi there, thank you for this project, it's truly awesome.
I'm wondering whether there's someone successfully running CRA 16.9+
and utilising this library. Upon trying to use the `<Dante/>` component I'm left with the following error: 

```
`Error: Element ref was specified as a string (editor) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.`
```

Any help is appreciated and again thanks for this great library.

**Comment by searchableguy** [comment]
I tried to make it work with react@experimental but it doesn't. Facing same issues.

**Comment by michelson** [comment]
you need to dedupe react dependences, see bullet 3. you have multiple copies of react loaded.
usually this is solve by resolve alias of react on webpack config

something like:
```js
     ....
     resolve: {
      alias: {
        react: path.resolve('./node_modules/react'),
     }
    ....
}
```

**Comment by fabdrol** [comment]
@michelson I'm seeing this error, but using Typescript (tsc). How do I handle this? Seems like an odd bug.

**Comment by kishan-tocca** [comment]
> @michelson I'm seeing this error, but using Typescript (tsc). How do I handle this? Seems like an odd bug.

facing same issue

**Comment by alxAgu** [comment]
Same here. Why was this even closed? 

@fabdrol, did you manage to solve it?
