### ISSUE TITLE
Not usable

### ISSUE THREAD

**Issue by Quix0tic** [michelson/dante2#214]
I really love how the editor behaves on your hosted demo.
Unfortunately, there is a whole difference between the demo and a simple test app in React.

I have a very hard time implementing the editor: Errors importing libraries, types not found, documentation very vague.
Once I got it up and running it was full of glitches: tooltip opening in wrong positions, cannot select text using `ctrl+shift+arrow`, etc.

So I decided to `git clone` but I am still not able to run a successful build.

Oh man, I'd really love to contribute in some way...

**Comment by michelson** [comment]
What version have you installed ?

**Comment by Quix0tic** [comment]
I have tried both `latest` and `next`

**Comment by michelson** [comment]
Hi, this is an example of the latest version 0.5.0-rc25 , it's working just fine. https://stackblitz.com/edit/react-zorwjl , it's a good starting point for you to start , I guess.

If you are going to report an issue please do it with more detail, screenshots, code traces - if errors - or a repo that I can use to replicate the same error as you. 
It's worthless that you tell us that you have a bad time implementing it and expect to get an answer from us and solve your issue. it's a waste of time for both. 

Also you can do some research of issues already closed before write your own.

here is an screen recording of selecting with control+shift+arrow or shift arrow
http://g.recordit.co/ZZlDYps7iI.gif . 

If you have specific issue I would expect more detail , browser version and a screen recorded would be helpful.

I'm going to close this issue now

**Comment by Quix0tic** [comment]
Turns out that after deleting `node_modules` and `package-lock.json` it fixed itself.

Sorry for wasting your time.
