### ISSUE TITLE
On init console warning 

### ISSUE THREAD

**Issue by asrebo** [michelson/dante2#218]
when i include Dante2 in my project i get warning in my console several times:

_Warning: A string ref, "editor", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided. We recommend using useRef() or createRef() instead. Learn more about using refs safely here: https://fb.me/react-strict-mode-string-ref_

and also when im passing prop  "save_handler={ function (editorContext, content){...}}" it never gets called

i'm curenty using latest version of react

**Comment by garmjs** [comment]
The warning goes away when you build the project for production, btw are you on `v0.5.0-rc25` because I'm not receiving this warning

**Comment by garridio85** [comment]
I get the same when using both 0.5.0-rc4 and  v0.5.0-rc25

react: 16.13.1
react-dom: 16.13.1
