### ISSUE TITLE
Target blank for links

### ISSUE THREAD

**Issue by MaartenBloemen** [michelson/dante2#222]
Hi!

Is it possible to configure all `<a>` tags to blank targets for the `href` and not just the link in the pop over?

I have looked trough the documentation and searched in the issues but I could not really find anything regarding this. Any help would be appreciated, thanks in advance!

**Comment by garmjs** [comment]
Yes you can use [draft-convert](https://www.npmjs.com/package/draft-convert) and add 

```
entityToHTML: (entity, originalText) => {
        if (entity.type === 'LINK') {
          return <a target=”_blank” href={entity.data.url}>{originalText}</a>;
        }
        return originalText;
      }
```
