### ISSUE TITLE
save_handler is not working with images

### ISSUE THREAD

**Issue by HugoSanchez** [michelson/dante2#224]
Hi Michelson, 

I'm having trouble working with images, as the save_handler custom function stops working after I upload an image. All I'm doing for the moment is console.log(content) to see how the image looks like.

I'm working with Dante2 version "^0.5.0-rc21", and I have also installed @emotion/core, @emotion/styled, emotion-theming as explained in this issue [178](https://github.com/michelson/dante2/issues/178) 

Any clue on what I might be doing wrong?

Thank you, 
Hugo

**Comment by michelson** [comment]
Hi @HugoSanchez please use the latest version and if you can send us a codesandbox with an example app to reproduce the error or the trace error and code sample

**Comment by HugoSanchez** [comment]
Hi @michelson, using the latest version made it work, sorry for that!

**Comment by michelson** [comment]
no worries, glad it work!
