### ISSUE TITLE
Dante 2 on change not working next js

### ISSUE THREAD

**Issue by K-Kumar-01** [michelson/dante2#236]
I have currently installled dante0.5.0-rc25
i am trying to use it in next js 
however the onChange  is not woring

# My code

import React from 'react';
import Dante from 'Dante2';

const ArticleCreate = () => {
	return (
		<div className={`container`}>
			<Dante
				onChange={(editor) => {
					console.log('editor content: ', editor.emitSerializedOutput());
				}}
			/>
		</div>
	);
};

export default ArticleCreate;

DANTE WARNING
Warning: Prop `id` did not match. Server: "placeholder-7d9df" Client: "placeholder-9gknp"

main.js:19205 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DanteImagePopover, DanteInlineTooltip, DanteTooltipColor
printWarning @ main.js:19205
main.js:19205 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DraftEditor

**Comment by K-Kumar-01** [comment]
Started working need to update 
My apologies

**Comment by michelson** [comment]
great!

**Comment by philmetzger** [comment]
> Started working need to update
> My apologies

How did you get it working @K-Kumar-01 ? I have 0.5.0-rc26 installed but still not able to console.log and also still have that id issue.

**Comment by K-Kumar-01** [comment]
> > Started working need to update
> > My apologies
> 
> How did you get it working @K-Kumar-01 ? I have 0.5.0-rc26 installed but still not able to console.log and also still have that id issue.

@philmetzger  `yarn install` simply wont work.
you have to also run `yarn update`.
As far as i can interpret, the thing is that some of the dependencies on which Dante depends are not fulfilled using yarn install
so yarn update updates them and it starts working.
