### ISSUE TITLE
onChange not being triggered

### ISSUE THREAD

**Issue by philmetzger** [michelson/dante2#237]
I have Dante2 set up as follows:

`<Dante
                    onChange={editor => { console.log('editor content: ', editor.emitSerializedOutput()) }}
                 />`

However when I start typing or so, the onChange is never triggered so I never see my console.log.
I am basically trying to figure out how to get the content to send it to the database and save it.

I am using: 0.5.0-rc16 but I also tried 0.5.0-rc4 and both dont trigger the onChange

**Comment by michelson** [comment]
please refer to existing issues like , https://github.com/michelson/dante2/issues/236

and check the examples on the page, if you still have problems, please submit a codesandbox example with your issue

thanks

**Comment by philmetzger** [comment]
The thing is @michelson when i run `npm install Dante2@next` (on my next js instance) it installs  `"Dante2": "^0.5.0-rc4",`
So not sure how the linked issue will help me. I did a fresh install/update.

**Comment by noerarief23** [comment]
> The thing is @michelson when i run `npm install Dante2@next` (on my next js instance) it installs `"Dante2": "^0.5.0-rc4",`
> So not sure how the linked issue will help me. I did a fresh install/update.

I have same problem, reinstall Dante2@nest not change anything

**Comment by michelson** [comment]
Hi , sorry guys , the latest version is 0.5.0-rc26
try that and see how it works

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>
