### ISSUE TITLE
How to upload images

### ISSUE THREAD

**Issue by NicolasDrapier** [michelson/dante2#238]
Hello,
I want to knwo how images are uploaded to the server ?
When I insert an image, the url is a blob like this:
![image](https://user-images.githubusercontent.com/33694593/94277336-b73ac900-ff49-11ea-8ae2-2803437aaf0e.png)
And it's not working because I can't see the image.
I tried [this](https://github.com/michelson/dante2/issues/175) but not working for me.

So I tried to upload image on Cloudinary, and get the URL.
Now I have a correct URL:
![image](https://user-images.githubusercontent.com/33694593/94277495-efdaa280-ff49-11ea-8cc6-d561c1cd6f4a.png)
But not rendered in the view
![image](https://user-images.githubusercontent.com/33694593/94277534-fcf79180-ff49-11ea-9f5e-8d89bcb73c2a.png)

What's wrong ?

**Comment by michelson** [comment]
Hi , blobs are the first step on the upload, those are useful for preview the upload image, then you will need to setup a callback to take the blob and send it to the server, the feature is documented on https://michelson.github.io/dante2/#/src-widgets and you can check the example file on the repo.
