### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by NicolasDrapier** [michelson/dante2#239]
Hi there,

Following this [issue](https://github.com/michelson/dante2/issues/238), I followed the doc and used it with my cloud service (Cloudinary). The image is well uploaded, and I recover well the url that updates in the block as you can see.

![image](https://user-images.githubusercontent.com/33694593/94336188-7ee6c980-ffe1-11ea-830a-90d05e170a38.png)

Unfortunately, when I save the content and display it on another page with <Dante content={my_content}/ retrieved from the database, everything is displayed except the images.

My code :
```js
const Editor = () => {
  return <Dante
    body_placeholder={'Try to write'}
    onChange={editor => { myEditor = editor }}
    widgets={[
      ImageBlockConfig({
        options: {
          upload_url: "my_special_url_that_works_well",
          upload_callback: (ctx, img) => {
            alert('file uploaded: ' +
              ctx.data.url)
          },
          upload_error_callback: (ctx,
            img) => {
            console.log(ctx)
          },
        },
      }),
    ]} />;
};
```

Need some help?

Thank you very much.

**Comment by michelson** [comment]
Hi Nicholas, what happens when you inspect the block on chrome dev tools? is the image tag shown ?
what happens on react dev tools ? did the block get the proper props ?

**Comment by NicolasDrapier** [comment]
Hi ! 
Thank you for your answer !

First, when I upload an image using the widget, it prints an alert with the URL as expeted. And if I check my cloud service, the image is uploaded.

If I display the content:
![image](https://user-images.githubusercontent.com/33694593/94360771-48c44b00-00b0-11eb-9b16-d4a15e0c4f0c.png)

And the console log of blocks:
![image](https://user-images.githubusercontent.com/33694593/94360810-77422600-00b0-11eb-9e8c-527e9d689a84.png)

In my cloud service:
![image](https://user-images.githubusercontent.com/33694593/94360828-92ad3100-00b0-11eb-9e88-44abd7377e4e.png)

And the block props with the react dev tools :
![image](https://user-images.githubusercontent.com/33694593/94360908-fc2d3f80-00b0-11eb-8c54-9bea443202be.png)

I can't see what looks wrong :(
Nicolas

**Comment by michelson** [comment]
Uhmm thats wierd, can you paste the generated html too?

**Comment by NicolasDrapier** [comment]
In the src property of image, I replace my cloud bucket with "mycloud" before paste it

```html
<div data-contents="true">
   <h1 class="graf graf--h2 is-selected" data-block="true" data-editor="3in64" data-offset-key="ar27o-0-0">
      <div data-offset-key="ar27o-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="ar27o-0-0"><span data-text="true">This is a test for images</span></span></div>
   </h1>
   <figure class="graf graf--figure  " data-block="true" data-editor="3in64" data-offset-key="3qajd-0-0" contenteditable="false">
      <div>
         <div class="aspectRatioPlaceholder is-locked">
            <div class="aspect-ratio-fill"></div>
            <img src="http://res.cloudinary.com/mycloud/image/upload/v1601197005/grlencrfccjmyzeuhulj.jpg" class="graf-image" contenteditable="false" alt="http://res.cloudinary.com/mycloud/image/upload/v1601197005/grlencrfccjmyzeuhulj.jpg">
            <div></div>
         </div>
         <figcaption class="imageCaption">
            <div data-offset-key="3qajd-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="3qajd-0-0"><span data-text="true">This is the image caption</span></span></div>
         </figcaption>
      </div>
   </figure>
</div>
```

If I paste just the <img> tag generated in a new html file , the image is shown:
![image](https://user-images.githubusercontent.com/33694593/94369294-269aef00-00e9-11eb-8502-61a6e6761118.png)

Is it a bug in my project ?

**Comment by michelson** [comment]
thing is, there is an aspect ratio div that should have a height value: like this:

![image](https://user-images.githubusercontent.com/11976/94370248-49b3a780-00c5-11eb-9039-ac5a05209dda.png)

the block must have this state :

![image](https://user-images.githubusercontent.com/11976/94370287-81225400-00c5-11eb-8285-7da213d873a3.png)

which version of dante2 are you using ?

**Comment by NicolasDrapier** [comment]
I'm using Dante2 v0.5.0-rc9

**Comment by michelson** [comment]
ok, try `0.5.0-rc26` , let me know how it goes

**Comment by NicolasDrapier** [comment]
It still doesn't work :(
When I hovered my mouse on the image link, it displayed this
![image](https://user-images.githubusercontent.com/33694593/94370779-37039780-00f2-11eb-970e-8effc1fbf689.png)

I think the 0px is the problem

**Comment by michelson** [comment]
do you have some link where I can see your implementation ?

**Comment by NicolasDrapier** [comment]
My repo is private, is it ok if I add you temporarily as a collaborator ?

**Comment by michelson** [comment]
sure , no problem

**Comment by NicolasDrapier** [comment]
It's ok, 
I'm using MeteorJS 10
Look at imports/ui/component/editor.js and imports/ui/pages/focus/id_focus.js
