### ISSUE TITLE
Import as es6 needs some rework

### ISSUE THREAD

**Issue by reimertz** [michelson/dante2#24]
Right now, everything gets built into `/docs` which is mainly for the documentation page.

I think this project needs to look at how other React-based libs are doing it. Most of them build several builds for
- npm module
- es module
- bower module
- distributable

npm/bower/distributable for `window.Dante` and es for `import { Dante } from 'Dante2'`.

**Comment by Bodacious** [comment]
Are these new ES6 changes widely supported? 

My test suite is breaking because PhantomJS (2.1) doesn't support `String#startsWith()`

Here's the supported versions for that http://www.w3schools.com/jsref/jsref_startswith.asp

Is there any way to avoid these newer functions?

**Comment by michelson** [comment]
it depends on how you will integrate the library. 
are you using the es6 modules or the files from dist ?

**Comment by Bodacious** [comment]
I'm using the Rails gem, which loads static files from the `/docs` directory (which isn't a great setup).

**Comment by michelson** [comment]
right , we should update rails gem in order to use dist instead of docs

**Comment by Bodacious** [comment]
I'm on it

**Comment by michelson** [comment]
Gavin, I think this will be the correct paths for rails pipeline

    config.assets.paths << Dante2Editor::Engine.root.join("dist")
    config.assets.paths << Dante2Editor::Engine.root.join("src", "styles")
    config.assets.paths << Dante2Editor::Engine.root.join("src", "styles",
"fonts")
    config.assets.paths << Dante2Editor::Engine.root.join("src", "images")

I will commit it very asap

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by Bodacious** [comment]
I just tried. Looks good in theory, but when I run it in my app I get 

```
[Error] TypeError: undefined is not an object (evaluating 'i.createElement')
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:6:12386)
	e (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:514)
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:3:3548)
	e (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:514)
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:22:21341)
	e (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:514)
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:656)
	e (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:514)
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:598)
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:602)
	(anonymous function) (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:300)
	Global Code (Dante2.min.self-b6818519fe1fa88f4d2b4e6a7e27fcd9c4286f9814f2436c932f7dfcd1c82932.js:1:321)
[Error] ReferenceError: Can't find variable: Dante
	(anonymous function) (posts.self-56c8baebd63c9366b09993b2d40f39455844d3b8ce69aa4f9bdba96928ad39a0.js:16)
	dispatch (jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js:5227)
	handle (jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js:4879)
	dispatchEvent
	dispatch (turbolinks.self-c5acd7a204f5f25ce7a1d8a0e4d92e28d34c9e2df2c7371cd7af88e147e4ad82.js:6:899)
	notifyApplicationAfterPageLoad (turbolinks.self-c5acd7a204f5f25ce7a1d8a0e4d92e28d34c9e2df2c7371cd7af88e147e4ad82.js:6:32467)
	pageLoaded (turbolinks.self-c5acd7a204f5f25ce7a1d8a0e4d92e28d34c9e2df2c7371cd7af88e147e4ad82.js:6:30855)
	(anonymous function) (turbolinks.self-c5acd7a204f5f25ce7a1d8a0e4d92e28d34c9e2df2c7371cd7af88e147e4ad82.js:6:27069)
```

Also, it would be nice (but not essential) to have some symmetry between the CSS and JS filenames.

So that including them in asset manifests would look like

    // In JS
    //= require Dante2.min

    # in SASS
     @import "Dante2.min"

**Comment by michelson** [comment]
check latest version 0.3.1 it comes with module support. also check the example on how to use this as a react component https://github.com/michelson/dante2-tests
cheers
