### ISSUE TITLE
Dante Editor not rendering content

### ISSUE THREAD

**Issue by anup-a** [michelson/dante2#241]
I fetching initial content using useEffect hook

```js
useEffect(() => {
    if (isEditing) {
      if (loading || error) {
        return
      }
      const postResponse = data.getPostById
      const postDetails = postResponse.post
      setBodyText(JSON.parse(postDetails.body))
  }, [error, loading, isEditing, data])
```

But, when the content is set in Dante component , there is no content.
```html
<Dante
       className="blog-editor"
       content={bodyText}
       onChange={(editor) => handleChange(editor)}
/>
```
At the other place where I just populate content with variable it works, but it doesn't work in this case where I'm setting data in useEffect?

**Comment by anup-a** [comment]
Fix - You just have to wait for state to set with initial data i.e., make a variable "initializing", make it true after data loads in useEffect. Then render dante as ` initializing && <Dante ... />`

**Comment by noerarief23** [comment]
> Fix - You just have to wait for state to set with initial data i.e., make a variable "initializing", make it true after data loads in useEffect. Then render dante as ` initializing && <Dante ... />`

can you give me full sample?

**Comment by anup-a** [comment]
> > Fix - You just have to wait for state to set with initial data i.e., make a variable "initializing", make it true after data loads in useEffect. Then render dante as ` initializing && <Dante ... />`
> 
> can you give me full sample?

@noerarief23 take [this](https://github.com/MomenSherif/blogging-reactjs/blob/master/src/pages/BlogForm/index.js) file as example

Here, `loading` is set true initially and dante isn't rendered (because `{!loading && <compo...` ), but when useEffect hook is called loading is set to false, and component renders with initialized data.
