### ISSUE TITLE
How to add another side button without forking the library ?

### ISSUE THREAD

**Issue by StarAzure** [michelson/dante2#244]
Is there a way to add another button when the + is clicked? Not looking to bring a brand new toolbar but looking to add an additional button on top of the existing ones.

Unfortunately, the docs just show one line code and not the underlying code:
https://michelson.github.io/dante2/#/src-tooltips

Also, this particular example from docs, just replaces the existing button entirely with a single new button. What if we want to just add a new button instead of replacing existing buttons?
```
<
Dante
content
={null}
tooltips
={[DanteInlineTooltipConfig()]}
widgets
={[CustomWidgetconfig()]}
/>
```

According to the Github page, doing is is easy:

> Add or remove tooltip buttons with ease with plugin system.
> Add custom blocks many with custom options

Thanks

**Comment by abrahamjsb** [comment]
I have the same issue, but it seems to be reached by forking the library I'm afraid.

**Comment by StarAzure** [comment]
I had to pick another library unfortunately as there are limitations with this and no response from author makes me worry about long term maintenance. Thanks.

**Comment by abrahamjsb** [comment]
What library do you pick instead? I'm afraid that I'm running out of time and fork is more work that is should be.
