### ISSUE TITLE
issues with save_handler and immutability when trying to update entries

### ISSUE THREAD

**Issue by FilipGal** [michelson/dante2#245]
Hello,

I am trying to get the `save_handler` function to work with posting and updating entries. However, from skimming through the source code, it would appear as if the object created from the `save_handler` function is immutable. As such, the Id which I need in order to update an entry will always be 0.

[Here](https://repl.it/repls/MiniMistyForm#index.ts) is a code example on repl.it, note that I use TypeScript but just ignore the types.

Is there any way I can override `save_handler` somehow, despite it being immutable?

Version used is 0.5.0-rc26.

**Comment by michelson** [comment]
Hi , the code is not working on repl, but I think you can do this in your function

```
if (id > 0) {
    return await api.json.post('update existing endpoint', {
         id: functionToGetId(),
         content: JSON.stringify(content),
    })
}
```

**Comment by FilipGal** [comment]
Hi,

Thanks for your reply, I am happy to say that your suggestion worked.

Instead of passing id as an argument that was provided from useState I instead did the following

```typescript
const getContentId = async () => {
    const { success, data } = await api.json.get(
        '/EditableContent/GetEditableContent',
        {
            id: <random id from db that I want to test with>,
        },
    )

    return success ? data.id : 0
}

const saveEditorContent = async (content: IEditorSerializedOutput) => {
    const id = await getContentId()

    if (id > 0) {
        return await api.json.post('/EditableContent/UpdateEditableContent', {
            id,
            content: JSON.stringify(content),
        })
    }

    return await api.json.post('/EditableContent/SaveEditableContent', {
        content: JSON.stringify(content),
    })
}
```

Thanks for the help!

**Comment by michelson** [comment]
note that you are going to fetch the server for the id on every save.
maybe you can fetch the id once and reuse that

**Comment by FilipGal** [comment]
I know, but I appreciate that you are pointing it out! I will make the necessary adjustments in terms of QA, just wanted to see if I could get it to work per your recommendation 👍
