### ISSUE TITLE
onChange not work!

### ISSUE THREAD

**Issue by noerarief23** [michelson/dante2#246]
iam using yarn add Dante2@next
"Dante2": "^0.5.0-rc4",
"react": "^16.13.1",

onChange={editor => { console.log('editor content: ', editor.emitSerializedOutput()) }}

any solutions? console not shown

**Comment by Earvin-Pepito** [comment]
@noerarief23 I'm running React 16.13.0 with rc4 and hit the same roadblock as you. I eventually got it working by updating to rc9. Be sure to install prismsjs with it or it won't work.

**Comment by noerarief23** [comment]
> @noerarief23 I'm running React 16.13.0 with rc4 and hit the same roadblock as you. I eventually got it working by updating to rc9. Be sure to install prismsjs with it or it won't work.

"Dante2": "0.5.0-rc9" and install prismjs
Thank you @Earvin-Pepito , works!
