### ISSUE TITLE
Tooltip link assumes base URL

### ISSUE THREAD

**Issue by AndrewBMartin** [michelson/dante2#248]
Dante2 version: 0.5.0-rc25

When I enter a URL in the link input after selecting link in the tooltip bar, the URL I enter gets appended to my app base URL. 

For example: my base URL is http://localhost:3000 and I enter my link URL to be "www.github.com" then the link is saved as http://localhost:3000/www.github.com.

Unless I'm missing something, this makes linking to external pages impossible.

**Comment by michelson** [comment]
it will work if you add a valid uri with protocol (https / http), I guess the ux could be improved appending a default protocol if it does not have one
