### ISSUE TITLE
How to programatically get the state of editor ?

### ISSUE THREAD

**Issue by ricking06** [michelson/dante2#28]
how do i get the json state in order to save it in backend ? i dont find it in docs

**Comment by ricking06** [comment]
i checked out draft  but looks like `getcurrentcontent` is not working

**Comment by michelson** [comment]
Hi @ricking06 

You have to access the component editorState , try this in console on demo page: https://michelson.github.io/dante2/

`editor.editor.state.editorState.getE....`

**Comment by ricking06** [comment]
I can access the `editor.editor`  from the demo online. 
But in my own pc its undefined.

In online demo im getting `t {options: Object, editor: DanteEditor}` on `editor` object
But in my own pc im just getting `t {options: Object}`

```

	  document.addEventListener('DOMContentLoaded', function(){
        editor = new Dante(
          {
            api_key: "86c28a410a104c8bb58848733c82f840",
            el: "dante-editor",
            content: entity_start, 
			body_placeholder : 'Start Writing...',
            debug: true,
            data_storage: {
              url: "someurl"
            }
          }
        )
       x = editor.render();
      });

```

**Comment by ricking06** [comment]
Ok the problem is fixed looks like the package is not updated. Initially i build from npm but now i copied your scripts from your site it works fine.

**Comment by michelson** [comment]
reopen if you still have this issue, it should work with latest version with `editor.editor.state.editorState`
