### ISSUE TITLE
Is there any option for multiple placeholder in dante2 editor?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#32]
I want to insert two placeholders like :- 

- Title

- Write your text here.

How can I do that?

**Comment by michelson** [comment]
Hi @sheeshmohsin , right now the placeholder we use is the default from draft-js , it would be nice to build a more modular placeholder for D2

**Comment by sheeshmohsin** [comment]
Can you provide any guidelines on how to do it? so that i am able to work on it in my available timings.

**Comment by michelson** [comment]
there is a placeholder widget , it's used in embed url widget contexts

fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
