### ISSUE TITLE
How to generate public files for use in production?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#33]
I am not able to generate dante.css, dante.js, dante-vendors.js for use in a separate app, however I am able to use it with the demo cloned in local.

Also there are not guidelines on how to generate those?

Is there any docs regarding that?

P.S: I am not a node developer, and want to use it in my python project, just as css, and js urls, is that possible?

**Comment by michelson** [comment]
sure, just use the files from dist folder clone repo and run `yarn install` &&  `yarn build`
if you want to use the scss source check the this wiki https://github.com/michelson/dante2/wiki/Rails-styles-integration

**Comment by sheeshmohsin** [comment]
Hi,

Just one another query, I ran `yarn install` && `yarn build` , but not able to find any dist folder after running the command. where can I find it?

**Comment by sheeshmohsin** [comment]
Any updates on this issue?

**Comment by michelson** [comment]
Hi @sheeshmohsin , I've prepared a PR for builds but it's not ready . In the meantime the `yarn build` on master branch will create files on /docs , you can use them as are for production use.

**Comment by sheeshmohsin** [comment]
Hi @michelson I tried the copying the files generated in /docs in my python app, but in frontened its throwing this error. 

![screenshot from 2017-01-31 11-55-46](https://cloud.githubusercontent.com/assets/4139932/22454514/5d2cc61a-e7ac-11e6-8df5-7f4aa95d52ac.png)

**Comment by michelson** [comment]
ouch! no idea

maybe you could test it running `yarn run` and see if it's working on development server?

**Comment by sheeshmohsin** [comment]
Yeah, Its running fine on development server after running `yarn run` or `npm start`, but not after picking up the file for use in another app.

**Comment by sheeshmohsin** [comment]
So, what I got for now, If I want to use in separate app, I need to run a separate server of dante2, and use the urls of dante server for fetching css and js, is it?

**Comment by michelson** [comment]
check the latest version ( 0.3.1 ) it comes with a better distribution module support.
Also check the example on how to use `es6 modules` at  https://github.com/michelson/dante2-tests
let me know if you got more issues with this.

cheers

**Comment by sheeshmohsin** [comment]
I finally able to use the js and css file built in amd directory.
Below are the steps which I did and it starts working, may be someone can use this :- 

1. Comment out the externals part in `webpack/webpack.config.js` in `export default` as shown below :- 

    // externals: [
    //   {
    //     react: {
    //       root: 'React',
    //       commonjs2: 'react',
    //       commonjs: 'react',
    //       amd: 'react',
    //     },
    //   },
    //   {
    //     'react-dom': {
    //       root: 'ReactDOM',
    //       commonjs2: 'react-dom',
    //       commonjs: 'react-dom',
    //       amd: 'react-dom',
    //     },
    //   },
    // ],

2. Then Run `npm run build` and collect these files from amd directory `DanteStyles.css` , `Dante2.js`, `dante-vendors.js` , and you are ready to go.

**Comment by michelson** [comment]
related #48
