### ISSUE TITLE
Upload image to Amazon S3

### ISSUE THREAD

**Issue by LotharVM** [michelson/dante2#34]
Hi all,

In my application I'm using Multer for file uploads (and compression with TinyPNG) to S3, that works fine. Now, I'm looking for a way to use Multer and TinyPNg to optimize, store and return a link to the Dante editor for displaying images in blogs created by users of my application.

I saw some nice implementations of the Dante editor with, for example, imgur.com (https://asd.reimertz.co/create), so I'm pretty sure it should work with S3 as well. I just don't really know where to start here..

Any help would be highly appreciated!

Kind regards,
Lothar

**Comment by michelson** [comment]
yup , it should. Just upload and process the image in your backend and then return the link to dante on the configured upload url
