### ISSUE TITLE
Images are appearing as editable

### ISSUE THREAD

**Issue by Bodacious** [michelson/dante2#35]
When the editor is **not** in the editable state, images still appear to be editable when you click on them.

While these changes are not persisted, it doesn't look good to the end user.

<img width="677" alt="screenshot 2017-01-29 21 44 25" src="https://cloud.githubusercontent.com/assets/73998/22408186/8fc78f2e-e66c-11e6-99e5-184ac9fedb31.png">

**Comment by michelson** [comment]
yup , this is a nasty one. I will give this high priority
