### ISSUE TITLE
Is there any way to send only the changes done from the editor?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#36]
Right now, what I can see is, dante is sending the complete data on store url , is there any way to send only the changes did by the user and add it up in the backend? so that we can save some bandwidth from user side? and alternatively improve the user experience?

**Comment by michelson** [comment]
sure, I've though about it, I've seen that feature in medium the send deltas of content, also I've seen this feature in quill editor. Also I've seen some discussion in the draft-js repo.
https://github.com/facebook/draft-js/issues/93

**Comment by michelson** [comment]
Hi @sheeshmohsin , you can implement a diff https://github.com/kbadk/json0-ot-diff and send that , then you will need to merge that into the server side.

Due that this needs a server side implementation I will leave this to the implementer :D , it's not dante's concern to tackle this issue

best
