### ISSUE TITLE
How to set content if Its already present in db for providing user to edit their articles?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#38]
I tried this script for setting content in editor, but didn't got success, below is the script :- 

    $.getJSON("http://127.0.0.1:8081/fetch/", function(data){
      window.PocData = data;
      console.log(data);
      document.addEventListener('DOMContentLoaded', function(){
        editor = new Dante(
          {
            el: "app",
            content: data,
            upload_url: "http://127.0.0.1:8081/upload/",
            data_storage: {
              url: "http://127.0.0.1:8081/store/"
            }
          }
        )
        editor.render()
      });
    })

and below is the data format which I am fetching using getJSON :- 

    {u'text_content': u'sheesh mohsin', u'editor_content': u'{"entityMap":{},"blocks":[{"key":"46hh7","text":"sheesh mohsin","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}'}

Please provide more details.

**Comment by michelson** [comment]
is giving you errors in console ?

as I see it it should work fine

**Comment by sheeshmohsin** [comment]
Okay, I fixed this using JSON.parse on the received data. Thanks for your help :)
