### ISSUE TITLE
What's the use of sockjs?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#39]
I am using dante2 editor deployed from separate server as my app is written in python, so I am pinging another url where dante2 is deployed but there is a error in console which tries to ping some sockjs url.

Please look below in the pic
![screenshot from 2017-02-01 12-48-02](https://cloud.githubusercontent.com/assets/4139932/22498168/b135076a-e87c-11e6-8313-5e6c7c977bb3.png)

**Comment by sheeshmohsin** [comment]
Currently I can't see any issue because of this, just curious to know what's its use? and what are the drawbacks if i ignore this?

**Comment by michelson** [comment]
that seems to be webpack --hot
