### ISSUE TITLE
How to do server side rendering in dante2, while showing article to the user?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#40]
As far as I know, for showing articles or post, we needed to use dante2 editor in non editable mode for rendering the html, which doesn't works good for SEO optimizations. One needed to use server side rendering for proper SEO optimization. Is there any suggested way for SEO optimation of the articles or post? or Can someone please point me to the code where dante2 is converting the json markups to html, so that I can use in server side rendering?

**Comment by michelson** [comment]
you could use semantic markup and og meta tags to improve SEO, also there
is a thread in draft-js repo where you can see the current state of
isomorphic rendering https://github.com/facebook/draft-js/issues/385

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by michelson** [comment]
Also, another approach is to use solutions like prerender.io (or it's open source alternative)
