### ISSUE TITLE
Is there any documentation for converting json content into html?

### ISSUE THREAD

**Issue by sheeshmohsin** [michelson/dante2#41]
I would like to know like during the process of development of the editor, is there any documentation available in which its explained that what parameters are used in json and what all things can i use to convert it back to html?

**Comment by michelson** [comment]
as the Editorcontent is a core feature from draftJS you should read the documentation on draft'js site.
also you will find some libraries that allow the conversion from the EditorContent to html and vice versa.

**Comment by jameszmartin** [comment]
I would checkout out [Last Draft](https://github.com/vacenz/last-draft)s [convert](https://github.com/vacenz/last-draft/blob/master/src/utils/convert.js) method as a guide, which uses draft-convert.
