### ISSUE TITLE
Integration with Angular-CLI Project - (Angular2)

### ISSUE THREAD

**Issue by msaiyaff** [michelson/dante2#47]
Can this editor be integrated with angular(which framework's name has changed from angular2) project?
A project using angular-cli to build apps.

**Comment by michelson** [comment]
I don't use Angular so is not in my roadmap. But if you need help with the integration I will be glad to help. Does angular need something in particular for Dante2 to work ?

**Comment by msaiyaff** [comment]
@michelson I have done a bit of search and found that Draft JS is done with react and couldn't think of any solutions for angular 2 integration at the moment. Closing the issue. By the way thanks for the reply.

**Comment by michelson** [comment]
hey @msaiyaff , yup , draft-js is built on top of react, Anyway I believe that dante2 should work along with Angular apps. By the way, there was Angular integration of previous dante version (without react deps) check it out https://github.com/julianfox/angular-dante

cheers

**Comment by msaiyaff** [comment]
Hi @michelson 
I actually came across this after checking with Dante and Angular Dante. It looks really cool. Thanks
