### ISSUE TITLE
Put `immutable` into package.json

### ISSUE THREAD

**Issue by Youmoo** [michelson/dante2#5]
[`immutable`](https://github.com/michelson/dante2/blob/master/app/components/App.cjsx#L4) is used as a dependency , but there's no record in `package.json`

**Comment by michelson** [comment]
Hi @Youmoo, I think this is not needed as draft-js already has this dependency, so when draft-js is included you have immutable as a dependency for free.

best

**Comment by michelson** [comment]
reopen if needed
