### ISSUE TITLE
module.exports is readonly when using ES2015 modules.

### ISSUE THREAD

**Issue by mihap** [michelson/dante2#54]
Not compatible with webpack v2.2+

please check this: https://github.com/webpack/webpack/issues/4039

**Comment by michelson** [comment]
Hi @mihap , try this repo: https://github.com/michelson/dante2-tests
it's a test to integrate dante2 in a custom react component, it uses webpack 2.2.1

**Comment by michelson** [comment]
@mihap , are you still having trouble with webpack 2.2 ? have you tried date2-tests ?

**Comment by olriko** [comment]
Same probleme, I have try 'dante2-test' and : 

` error  in ./~/dante2-tests/index.js

Module parse failed: /Users/ohamon/Documents/Projects/v2/flickshot/node_modules/dante2-tests/index.js Unexpected token (299:6)
You may need an appropriate loader to handle this file type.
|   render(){
|     return(
|       <DanteEditor
|         content={demo}
|         config={ this.options }
`

**Comment by michelson** [comment]
fixed the problem in Dante2 0.4.0 , I've updated dante2-tests too, please reopen issue if you get something wrong.
