### ISSUE TITLE
How to use editorState? 

### ISSUE THREAD

**Issue by alihaddadkar** [michelson/dante2#57]
Hi Miguel.
1- I using this [ES6 modules](https://github.com/michelson/dante2-tests/). I want get content from editor with editorState. How do I access editorState?

2- draft-js default way for focus when page loads, does not work in Dante.

**Comment by michelson** [comment]
Hi @alihaddadkar , the Editor component has an state property were you can access editorState.
in [demo page ](https://michelson.github.io/dante2/) you can access editorState running this in console: `editor.editor.state.editorState` 

Also you have the `save` utility, were you can obtain the editor text content: in the demo you it will work with `editor.editor.save.getTextFromEditor(editor.editor.save.editorContent)`

**Comment by alihaddadkar** [comment]
@michelson 
get error in console when used this code => `editor.editor.state.editorState`
`Uncaught TypeError: Cannot read property 'state' of undefined`

**Comment by michelson** [comment]
@alihaddadkar that example works in the demo page, as I said. because the variable `editor` is global.
