### ISSUE TITLE
How to use onChange?

### ISSUE THREAD

**Issue by jaspersorrio** [michelson/dante2#58]
How do i update the model onChange ?

Following https://michelson.github.io/dante2/doc.html, I am using ```new Dante({ el: "app"})``` to initialise the Editor.

Thank You!

**Comment by michelson** [comment]
there are some ways on how onChange is triggered. in general this is automatic when you use the editor.
what are you trying to accomplish ?

**Comment by jaspersorrio** [comment]
I'm trying to store the current state of the editor in redux. Using this with redux form v6. 

Somehow I managed to get it working by using data storage save handler method to update the store.

**Comment by michelson** [comment]
Hi , I have not use Redux with draftJs, but after googling a bit I found this: https://www.caffeinecoding.com/react-redux-draftjs/ , maybe it helps you

**Comment by jaspersorrio** [comment]
Thanks for the quick reply. Anyway, I've solved my problem by using the save_handler method.

**Comment by zcmgyu** [comment]
@jaspersorrio You save my day. I don't know why but when It's missing url: "/store" it doesn't work for me.
