### ISSUE TITLE
disable tooltip "DanteImagePopover"

### ISSUE THREAD

**Issue by gbu-censhare** [michelson/dante2#61]
Hi,

is there a way to disable the DanteImagePopover tooltip?
we don't need/want the alignment chooser in our project..

Thanks,
Georg

**Comment by michelson** [comment]
yes, when configure your tooltips just omit the `DanteImagePopover`

**Comment by gbu-censhare** [comment]
but, how do i "omit it", do i have to repeat then every other option? 

```
    let editor = new Dante(
      {
        tooltips: [
          {},
          {},
          {},
          { /* tooltip */ ref: 'xxxxx'}
        ],
}
```

i tried to just remove it from the my list, which didn't have any effects, setting ref to something different also doesn't change anything, when i set the component to undef or something like that, an exception is thrown....
