### ISSUE TITLE
video caption strange

### ISSUE THREAD

**Issue by gbu-censhare** [michelson/dante2#64]
When Inserting a Video the Caption is the URL of the Video (minus the "h" from http://) ..

Tested with:
https://www.youtube.com/watch?v=2hpVVv493Uw

**Comment by gbu-censhare** [comment]
![bildschirmfoto 2017-06-23 um 13 06 55](https://user-images.githubusercontent.com/12797061/27479657-12b9a560-5815-11e7-8fe3-93ddda89587b.png)

**Comment by entregrammer** [comment]
same here.

**Comment by michelson** [comment]
thanks , I will try to hit this issue this week

**Comment by zcmgyu** [comment]
Same here :D

**Comment by michelson** [comment]
fixed in 0.4.2 🎉
