### ISSUE TITLE
Paste (Cmd+v) not working 

### ISSUE THREAD

**Issue by anothermohit** [michelson/dante2#65]
The text copied (cmd+c) from the editor content is not getting pasted (cmd+v) while copied text from outside is working fine.

**Comment by rambabusaravanan** [comment]
For me, pasting works, but replaces the entire line no matter where the cursor is placed.
In this case, paste operation is useless.

dante2@0.5.0-rc1
react{,-dom}@16.6.3

**Comment by michelson** [comment]
Hi @rambabusaravanan I've fixed the behavior. can you check it out the PR #136 

thanks for report this

**Comment by michelson** [comment]
released as dante2@0.5.0-rc6
