### ISSUE TITLE
The futur of dante2

### ISSUE THREAD

**Issue by BafS** [michelson/dante2#70]
Hi,

First of all, I want to thank you for this project, I think it's probably the best medium-like editor with Draftjs. In the other hand, the project seems not really active and I wanted to know if you have plans to upgrade dante2 to React 16 and the last version of Draftjs (a lot of depreciations need to be updated for that). 

Thanks in advance !

**Comment by michelson** [comment]
Hi! I've updated the dependencies on Dante2, I've seen that is working fine , could you point out where are the deprecation warnings ?

**Comment by BafS** [comment]
With React 16 and Draft 0.10.3 I have those kind of warnings

```
WARNING: DraftEntity.mergeData will be deprecated soon!
Please use "contentState.mergeEntityData" instead.

WARNING: DraftEntity.get will be deprecated soon!
Please use "contentState.getEntity" instead.
```

**Comment by michelson** [comment]
Thanks @BafS , 
do you see those deprecation warnings when compile project with `yarn start` ? or `yarn build` ?

**Comment by BafS** [comment]
With `yarn start`. It appear with Draft 0.10.

**Comment by BafS** [comment]
I just tried your pull and it's the same warnings. Are you sure you see the "warnings" ?

![image](https://user-images.githubusercontent.com/588205/31412839-f89410be-ae16-11e7-9aac-708a557379a5.png)

The problem is with the static methods from Entity (ex `Entity.get(entityKey).getType()` in find_enties.js line 9).

**Comment by michelson** [comment]
Ah, I get it now, 
I've commited some changes in the PR #71 , there is only one deprecation now, I will try to fix this soon

**Comment by BafS** [comment]
Great, thank you

**Comment by BafS** [comment]
Would it be possible to push the new version on npm ? Thanks in advance !

**Comment by BafS** [comment]
Hi @michelson, any news about the PR ?

**Comment by michelson** [comment]
merged! thanks
