### ISSUE TITLE
manual save

### ISSUE THREAD

**Issue by FinnFrotscher** [michelson/dante2#74]
how do I save the content? including images, floats, etc. `this.stateToHTML(this.article.editor.getEditorState().getCurrentContent())` returns just the html without images.
I dont save directly via REST endpoint. Fist I bundle the content with more content, title and meta information.

**Comment by michelson** [comment]
Hi @FinnFrotscher , you have to save the EditorState, it's a json structure that DraftJs provides , it has all the information you need, styles & props of custom components like uploaded images. I don't recommend to save html to database, instead use the EditorState.
The editor has an option called `save_handler` in which you can build your own callback in order to receive the editorState an store it anywhere. check the docs at: `https://michelson.github.io/dante2/doc.html`
Dante will check if your content changes and will trigger the save bahavior when is needed.

best!

**Comment by FinnFrotscher** [comment]
I passed a function to save_handler, but its not being called:
```
buildDante({ Dante }) {
    this.article = new Dante({
      el: "dante-editor",
      data_storage: {
        save_handler: (editorContext, content) => {
          console.log(editorContext, content)
        }
      },
      content: null
    })
    this.article.render()
  }
```

**Comment by michelson** [comment]
hi @FinnFrotscher , `save_handler` property has to be inside `data_storage` , it's described in the docs https://michelson.github.io/dante2/doc.html

**Comment by michelson** [comment]
in your case the manual save would be something like: `this.article.editor.dispatchChangesToSave()` also you get the serialized content with: `this.article.editor.emitSerializedOutput()`

**Comment by FinnFrotscher** [comment]
solved ✅

**Comment by FinnFrotscher** [comment]
about the rendering of the content. 
is `Dante` supposed to be used for the reading of content aswell or do you solve this another way?

**Comment by michelson** [comment]
Yes, you can use the editor for reading , just pass readOnly=true when init Dante

**Comment by KumarAbhirup** [comment]
Hey, passing readOnly={true} does not work.
```
<Dante
        content={this.defaultContent}
        body_placeholder={'Write your next masterpiece ✍️'}
        onChange={async editor => { 
          await this.setState({ editor: editor.emitSerializedOutput() }) 
        }}
        readOnly={true}
      />
```
I can still edit with it!

Is there a way to get HTML from the serializedOutput?

**Comment by michelson** [comment]
it's `read_only` not `readOnly`

**Comment by KumarAbhirup** [comment]
hey thanks. `read_only` works.
But I see it's not server side rendered because I am using this:
```
import dynamic from 'next/dynamic'
const Dante = dynamic(import('Dante2'), {
  ssr: false
})
```

If I do the normal import, it says `document is not defined`!
I am creating blog-like webapp and seo is needed.

Any suggesstions for me?
