### ISSUE TITLE
Can not import DanteEditor

### ISSUE THREAD

**Issue by zcmgyu** [michelson/dante2#76]
Version: 0.3.6
import { DanteEditor, Dante } from "Dante2";
Throw below error.
> "export 'default' (imported as 'DanteEditor') was not found in './dante_editor.js'

**Comment by AaronGillBraun** [comment]
I'm also facing this issue. Really need a workaround!

**Comment by michelson** [comment]
Hi please try version 0.4.0 and the dante2-tests master version https://github.com/michelson/dante2-tests/. reopen this issue if you get something wrong

**Comment by zcmgyu** [comment]
Thanks, Dante2 0.4.0 works for me.
