### ISSUE TITLE
Can't import Youtube or Twitter link

### ISSUE THREAD

**Issue by zcmgyu** [michelson/dante2#79]
I tried paste a link youtube into your sample code. It seem like have no reaction.

http://www.giphy.com/gifs/l3mZm47gerVBxtPwI

**Comment by michelson** [comment]
which is your environment ? (OS & Browser)
As I can see in your gif you are not focusing into the placeholder. could be that , check this gif:

![img](http://g.recordit.co/rxZXG2xWVg.gif)

maybe the embed component needs to tackle more user cases, we can discuss that

**Comment by zcmgyu** [comment]
@michelson Thanks. I really didn't focus on placeholder. Please close it (bow)
