### ISSUE TITLE
Starting the editor with no content

### ISSUE THREAD

**Issue by AaronGillBraun** [michelson/dante2#83]
Is there a way to start the DanteEditor without any content (only displaying the placeholders) in the react component?
When I set the content prop to `{}`, `null`, or `''`, I get errors. (all essentially saying: you must supply a correct editorState object).

How can I set it so that I have a completely empty editor at the start?

**Comment by AaronGillBraun** [comment]
I fixed it by setting the starting state to:
```javascript
{"entityMap":{},"blocks":[{"key":"761n6","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}
```

which is the obj when the editor is empty.

Proposed adding this as a default if no content prop is supplied. (will work on)

**Comment by michelson** [comment]
Hi , I've noted that in latest version of draft the `null` value is not accepted as a content state at least in Dante2 implementation.  in order to fix this use this PR https://github.com/michelson/dante2/pull/81 , I will merge it soon.
