### ISSUE TITLE
Title Placeholder didn't show

### ISSUE THREAD

**Issue by zcmgyu** [michelson/dante2#84]
I released that you assigned the title placeholder option to DanteEditor. I seem like not work at all. Could you give me any hint?

defaultOptions.title_placeholder = "Title"
defaultOptions.body_placeholder = "Write your story"

**Comment by sakhmedbayev** [comment]
Yep, I am experiencing the same thing. Is `dante2` supported at all?

**Comment by michelson** [comment]
fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
