### ISSUE TITLE
Problem with currentContent when upgrade from 0.4.0 to 0.4.3

### ISSUE THREAD

**Issue by zcmgyu** [michelson/dante2#91]
Hi, Michelson. 
I try to get raw draft-js content from editorState.  Same code, different version of Dante2. I've released that with 0.4.3 version, entitiesMap and blocks have no data at all.

```
componentDidMount() {
        console.log("Get current editor state: ");
        const currentContent = this.editorState.getCurrentContent();
        console.log(convertToRaw(currentContent));
        console.log("Get first block:")
        console.log(currentContent.getFirst)
    }
    

    render() {
        return (
            <DanteEditor
                content={demo}
                ref={(danteEditor) => { this.editorState = danteEditor.state.editorState }}
                config={this.options}
            />
        )
    }
```

Version 0.4.0: 
![screen shot 2017-12-25 at 11 04 13 pm](https://user-images.githubusercontent.com/13638569/34341326-1499a2e6-e9c8-11e7-92f9-895957b75a6c.png)

Version 0.4.3
![screen shot 2017-12-25 at 11 04 33 pm](https://user-images.githubusercontent.com/13638569/34341332-1cd430c0-e9c8-11e7-9bee-c379612e6595.png)

**Comment by michelson** [comment]
with which content are you initialising editor ? in the Demo Page, as you can see , the entityMap is populated

**Comment by michelson** [comment]
since there is no response , I've closed this issue. reopen if needed
