### ISSUE TITLE
Popups showing up in the wrong place when editing.

### ISSUE THREAD

**Issue by bramski** [michelson/dante2#94]
See Screenshot.
![screen shot 2018-01-30 at 12 26 24 pm](https://user-images.githubusercontent.com/421781/35589555-234c07d6-05b9-11e8-9d7e-986593e75a0e.png)

**Comment by jerryc-nguyen** [comment]
@bramski I updated this issue. You can check my commit.

**Comment by michelson** [comment]
fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
