### ISSUE TITLE
how to act on changes to content area

### ISSUE THREAD

**Issue by noctivityinc** [michelson/dante2#95]
I need to hook into the change event for any content being added to the content area so that I can display a message to the user letting them know the document has not been saved (which I change to saved after the save_handler event.

How can I hook into this?

**Comment by michelson** [comment]
Hi @noctivityinc , 
use the `save_handler` , https://michelson.github.io/dante2/doc.html

**Comment by noctivityinc** [comment]
Now that only catches changes to SAVE.  We need changes on type.  We got it
working with this:

$('body').on('focus', '[contenteditable]', function() {
            var $this = $(this);
            $this.data('before', $this.html());
            return $this;
        }).on('blur keyup paste input', '[contenteditable]', function() {
            var $this = $(this);
            if ($this.data('before') !== $this.html()) {
                $this.data('before', $this.html());
                $this.trigger('change');
                $('#saveButton svg g').attr('fill','red')
            }
            return $this;
        });

**Comment by michelson** [comment]
that is not necessary , since the `save_handler` is executed on content change
