### ISSUE TITLE
Ruby gem is not compiling the font

### ISSUE THREAD

**Issue by noctivityinc** [michelson/dante2#97]
I am using the Ruby gem with Rails 5.1.5 and Ruby 2.5.0.  When we compile the assets, the font files dont appear to be included.  Take a look at this image:
<img width="473" alt="screen shot 2018-03-07 at 3 53 35 pm" src="https://user-images.githubusercontent.com/78850/37117678-e061191a-221f-11e8-86c3-4d2fda6e003f.png">

**Comment by michelson** [comment]
Please check the wiki on how to integrate the editor in rails
We are preparing a new release in which those issues will be fixed

**Comment by noctivityinc** [comment]
Sorry but this doens't work. The fonts still cannot be found.

**Comment by michelson** [comment]
ruby gem is deprecated , try the npm package, icons are now svg , there are no assets dependences besides the compiled css
this was fixed in 0.5.0-rc1 install as Dante2@next
also check the new documentation in github page
